import fs from 'node:fs';

const read = (path) => fs.readFileSync(path, 'utf8');
const fail = (message) => { console.error(`SECURITY CHECK FAILED: ${message}`); process.exitCode = 1; };
const requireText = (source, text, label) => { if (!source.includes(text)) fail(`${label} is missing ${JSON.stringify(text)}`); };
const forbidText = (source, text, label) => { if (source.toLowerCase().includes(text.toLowerCase())) fail(`${label} contains forbidden ${JSON.stringify(text)}`); };

const wranglerText = read('wrangler.jsonc');
const worker = read('src/index.ts');
const platform = read('src/platform.ts');
const hmlAuth = read('src/hml-auth.ts');
const hmlWorker = read('src/hml.ts');
const hmlBatch = read('src/hml-batch.ts');
const hmlMultimodal = read('src/hml-multimodal.ts');
const hmlFinal = read('src/hml-final.ts');
const hmlCommerce = read('src/hml-commerce.ts');
const hmlControl = read('src/hml-control.ts');
const panel = read('public/app.js');
const support = read('public/support.js');
const signup = read('public/signup.js');
const team = read('public/team.js');
const landing = read('public/index.html');
const n8nText = read('integrations/n8n/negociaja-hml-multimodal.json');
let n8n;
try { n8n = JSON.parse(n8nText); } catch { fail('n8n workflow JSON is invalid'); n8n = {}; }

const wrangler = JSON.parse(wranglerText);
if (wrangler?.main !== 'src/platform.ts') fail('Production SaaS platform gateway must remain the root Worker entry point');
if (wrangler?.assets?.run_worker_first !== true) fail('wrangler assets.run_worker_first must remain true');
if (wrangler?.d1_databases?.[0]?.binding !== 'DB') fail('D1 DB binding changed unexpectedly');
if (wrangler?.r2_buckets?.[0]?.binding !== 'FILES') fail('R2 FILES binding changed unexpectedly');
if (wrangler?.assets?.binding !== 'ASSETS') fail('ASSETS binding changed unexpectedly');
const hml = wrangler?.env?.hml;
if (!hml) fail('HML environment is missing');
if (hml?.name !== 'negociaja-hml') fail('HML Worker name changed unexpectedly');
if (hml?.main !== 'src/hml-control.ts') fail('HML must use the control/readiness isolated entrypoint');
if (hml?.workers_dev !== true) fail('HML must use workers.dev');
if (hml?.vars?.APP_ENVIRONMENT !== 'hml') fail('HML APP_ENVIRONMENT must be hml');
if (Array.isArray(hml?.routes) && hml.routes.length !== 0) fail('HML must not inherit production routes');
if (hml?.d1_databases?.[0]?.database_id === wrangler?.d1_databases?.[0]?.database_id) fail('HML must never bind production D1');
if (hml?.r2_buckets?.[0]?.bucket_name === wrangler?.r2_buckets?.[0]?.bucket_name) fail('HML must never bind production R2');

requireText(worker, 'cf-access-jwt-assertion', 'Core Worker');
requireText(platform, 'tenantPermission', 'Platform gateway');
requireText(hmlAuth, 'HML_PASSWORD', 'HML auth gateway');
requireText(hmlWorker, 'MAX_ASSET_BYTES', 'HML experience gateway');
requireText(hmlBatch, '/api/ops/overview', 'HML operational gateway');
requireText(hmlMultimodal, '/api/integrations/inbound', 'HML multimodal gateway');
requireText(hmlFinal, "url.pathname==='/api/ops/channels'", 'HML final gateway');
requireText(hmlCommerce, '/api/signup/request', 'HML commerce gateway');
requireText(hmlCommerce, '/api/billing/pix', 'HML commerce gateway');
requireText(hmlCommerce, 'X-Idempotency-Key', 'HML commerce gateway');
requireText(hmlControl, '/api/team', 'HML control gateway');
requireText(hmlControl, '/api/ops/diagnostics', 'HML control gateway');
requireText(hmlControl, '/api/ops/health/run', 'HML control gateway');
requireText(hmlControl, "current.role==='owner'", 'HML owner protection');
requireText(team, '/api/team', 'Team UI');
requireText(team, '/api/ops/diagnostics', 'Readiness UI');
requireText(signup, '/api/signup/request', 'HML signup UI');
if (n8n?.name !== 'NegocIAJá HML - Evolution Multimodal') fail('n8n workflow name changed unexpectedly');
if (!Array.isArray(n8n?.nodes) || n8n.nodes.length < 10) fail('n8n workflow is unexpectedly incomplete');
requireText(n8nText, 'OPENAI_API_KEY', 'n8n workflow');
requireText(n8nText, 'NEGOCIAJA_HML_URL', 'n8n workflow');
requireText(n8nText, 'EVOLUTION_API_URL', 'n8n workflow');
forbidText(n8nText, 'sk-proj-', 'n8n workflow');
forbidText(n8nText, 'cfut_', 'n8n workflow');
for (const [source,label] of [[worker,'Core Worker'],[platform,'Platform gateway'],[hmlAuth,'HML auth gateway'],[hmlWorker,'HML experience gateway'],[hmlBatch,'HML operational gateway'],[hmlMultimodal,'HML multimodal gateway'],[hmlFinal,'HML final gateway'],[hmlCommerce,'HML commerce gateway'],[hmlControl,'HML control gateway'],[panel,'Panel']]) forbidText(source, 'x-tenant-id', label);
forbidText(panel, '.innerHTML', 'Panel');
forbidText(panel, 'insertAdjacentHTML', 'Panel');
forbidText(panel, 'eval(', 'Panel');
forbidText(team, 'eval(', 'Team UI');
forbidText(hmlCommerce, 'APP_USR-', 'HML commerce gateway');
requireText(landing, 'O sistema se adapta ao seu negócio.', 'Landing');
if (process.exitCode) process.exit(process.exitCode);
console.log('Security regression checks passed.');
