import fs from 'node:fs';

const read = (path) => fs.readFileSync(path, 'utf8');
const fail = (message) => { console.error(`SECURITY CHECK FAILED: ${message}`); process.exitCode = 1; };
const requireText = (source, text, label) => { if (!source.includes(text)) fail(`${label} is missing ${JSON.stringify(text)}`); };
const forbidText = (source, text, label) => { if (source.toLowerCase().includes(text.toLowerCase())) fail(`${label} contains forbidden ${JSON.stringify(text)}`); };

const wranglerText = read('wrangler.jsonc');
const worker = read('src/index.ts');
const platform = read('src/platform.ts');
const hmlAuth = read('src/hml-auth.ts');
const hmlWorker = read('src/hml.ts');
const hmlBatch = read('src/hml-batch.ts');
const hmlMultimodal = read('src/hml-multimodal.ts');
const hmlFinal = read('src/hml-final.ts');
const hmlCommerce = read('src/hml-commerce.ts');
const hmlControl = read('src/hml-control.ts');
const hmlLab = read('src/hml-lab.ts');
const panel = read('public/app.js');
const signup = read('public/signup.js');
const team = read('public/team.js');
const labUi = read('public/hml-lab.js');
const landing = read('public/index.html');
const n8nText = read('integrations/n8n/negociaja-hml-multimodal.json');
let n8n; try { n8n = JSON.parse(n8nText); } catch { fail('n8n workflow JSON is invalid'); n8n = {}; }
const wrangler = JSON.parse(wranglerText);
if (wrangler?.main !== 'src/platform.ts') fail('Production gateway changed');
if (wrangler?.assets?.run_worker_first !== true) fail('assets.run_worker_first changed');
const hml = wrangler?.env?.hml;
if (!hml || hml?.name !== 'negociaja-hml') fail('HML environment missing');
if (hml?.main !== 'src/hml-lab.ts') fail('HML must use end-to-end lab entrypoint');
if (hml?.workers_dev !== true) fail('HML must use workers.dev');
if (Array.isArray(hml?.routes) && hml.routes.length !== 0) fail('HML must not inherit production routes');
if (hml?.d1_databases?.[0]?.database_id === wrangler?.d1_databases?.[0]?.database_id) fail('HML must never bind production D1');
if (hml?.r2_buckets?.[0]?.bucket_name === wrangler?.r2_buckets?.[0]?.bucket_name) fail('HML must never bind production R2');
requireText(worker,'cf-access-jwt-assertion','Core Worker');
requireText(platform,'tenantPermission','Platform gateway');
requireText(hmlAuth,'HML_PASSWORD','HML auth');
requireText(hmlWorker,'MAX_ASSET_BYTES','HML experience');
requireText(hmlBatch,'/api/ops/overview','HML ops');
requireText(hmlMultimodal,'/api/integrations/inbound','HML multimodal');
requireText(hmlFinal,"url.pathname==='/api/ops/channels'",'HML final');
requireText(hmlCommerce,'/api/signup/request','HML commerce');
requireText(hmlCommerce,'/api/billing/pix','HML commerce');
requireText(hmlControl,'/api/team','HML control');
requireText(hmlControl,'/api/ops/diagnostics','HML control');
requireText(hmlLab,'/api/hml-lab/simulate','HML lab');
requireText(hmlLab,'/api/hml-lab/trace','HML lab');
requireText(hmlLab,'integration_events','HML lab');
requireText(hmlLab,'integration_outbox','HML lab');
requireText(team,'/api/team','Team UI');
requireText(labUi,'/api/hml-lab/simulate','Lab UI');
requireText(labUi,'/api/hml-lab/trace','Lab UI');
requireText(signup,'/api/signup/request','Signup UI');
if (n8n?.name !== 'NegocIAJá HML - Evolution Multimodal') fail('n8n workflow name changed');
if (!Array.isArray(n8n?.nodes) || n8n.nodes.length < 10) fail('n8n workflow incomplete');
requireText(n8nText,'OPENAI_API_KEY','n8n workflow');requireText(n8nText,'NEGOCIAJA_HML_URL','n8n workflow');requireText(n8nText,'EVOLUTION_API_URL','n8n workflow');
forbidText(n8nText,'sk-proj-','n8n workflow');forbidText(n8nText,'cfut_','n8n workflow');
for (const [source,label] of [[worker,'Core'],[platform,'Platform'],[hmlAuth,'Auth'],[hmlWorker,'Experience'],[hmlBatch,'Ops'],[hmlMultimodal,'Multimodal'],[hmlFinal,'Final'],[hmlCommerce,'Commerce'],[hmlControl,'Control'],[hmlLab,'Lab'],[panel,'Panel']]) forbidText(source,'x-tenant-id',label);
forbidText(panel,'.innerHTML','Panel');forbidText(panel,'insertAdjacentHTML','Panel');forbidText(panel,'eval(','Panel');forbidText(team,'eval(','Team UI');forbidText(labUi,'eval(','Lab UI');forbidText(hmlCommerce,'APP_USR-','HML commerce');
requireText(landing,'O sistema se adapta ao seu negócio.','Landing');
if (process.exitCode) process.exit(process.exitCode);
console.log('Security regression checks passed.');
