/*
 * NegocIAJá! — desenvolvido pela SER Comunicação
 * CNPJ 23.296.513/0001-97
 * Todos os direitos reservados.
 */
import {Actor,Dict,Env,audit,authenticate,body,cents,json,makeId,resolveTenant} from './lib';

type ToolName='catalog.search'|'customer.lookup'|'order.lookup'|'order.prepare'|'order.create'|'order.status.change';
const READ_TOOLS=new Set<ToolName>(['catalog.search','customer.lookup','order.lookup','order.prepare']);
const WRITE_TOOLS=new Set<ToolName>(['order.create','order.status.change']);

async function searchCatalog(env:Env,tenantId:string,args:Dict){const q=String(args.query||'').trim();const category=String(args.category||'').trim();const limit=Math.min(50,Math.max(1,Number(args.limit||10)));const pattern=`%${q}%`;const result=await env.DB.prepare(`SELECT id,sku,name,description,item_type,category,unit,price_cents,stock_control,stock_qty FROM catalog_items WHERE tenant_id=? AND active=1 AND (?='' OR name LIKE ? OR description LIKE ? OR sku LIKE ?) AND (?='' OR category=?) ORDER BY name LIMIT ?`).bind(tenantId,q,pattern,pattern,pattern,category,category,limit).all();return result.results||[];}
async function lookupCustomer(env:Env,tenantId:string,args:Dict){const phone=String(args.phone||'').trim(),email=String(args.email||'').trim().toLowerCase(),document=String(args.document||'').trim();if(!phone&&!email&&!document)return[];const result=await env.DB.prepare(`SELECT id,name,phone,email,document,tags_json,created_at,updated_at FROM customers WHERE tenant_id=? AND ((?<>'' AND phone=?) OR (?<>'' AND lower(email)=?) OR (?<>'' AND document=?)) ORDER BY updated_at DESC LIMIT 10`).bind(tenantId,phone,phone,email,email,document,document).all();return result.results||[];}
async function lookupOrder(env:Env,tenantId:string,args:Dict){const code=String(args.public_code||'').trim(),id=String(args.id||'').trim();if(!code&&!id)return null;const order=await env.DB.prepare(`SELECT o.id,o.public_code,o.status,o.transaction_type,o.source,o.subtotal_cents,o.delivery_cents,o.discount_cents,o.total_cents,o.payment_status,o.fulfillment_type,o.notes,o.created_at,o.updated_at,c.name customer_name,c.phone customer_phone FROM orders o LEFT JOIN customers c ON c.id=o.customer_id WHERE o.tenant_id=? AND ((?<>'' AND o.public_code=?) OR (?<>'' AND o.id=?)) LIMIT 1`).bind(tenantId,code,code,id,id).first<any>();if(!order)return null;const items=await env.DB.prepare(`SELECT catalog_item_id,name,qty,unit_price_cents,total_cents,options_json FROM order_items WHERE order_id=? ORDER BY name`).bind(order.id).all();return{...order,items:items.results||[]};}
async function prepareOrder(env:Env,tenantId:string,args:Dict){const lines=Array.isArray(args.items)?args.items as Array<Record<string,unknown>>:[];if(!lines.length)throw new Error('Adicione pelo menos um item.');const resolved=[] as Array<Record<string,unknown>>;let subtotal=0;for(const line of lines){const catalogId=String(line.catalog_item_id||''),qty=Math.max(.001,Number(line.qty||1));const item=await env.DB.prepare(`SELECT id,name,price_cents,stock_control,stock_qty FROM catalog_items WHERE id=? AND tenant_id=? AND active=1 LIMIT 1`).bind(catalogId,tenantId).first<{id:string;name:string;price_cents:number;stock_control:number;stock_qty:number}>();if(!item)throw new Error(`Item inválido: ${catalogId}`);if(item.stock_control&&item.stock_qty<qty)throw new Error(`Estoque insuficiente para ${item.name}.`);const total=Math.round(item.price_cents*qty);subtotal+=total;resolved.push({catalog_item_id:item.id,name:item.name,qty,unit_price_cents:item.price_cents,total_cents:total});}const delivery=cents(args.delivery_cents),discount=Math.min(subtotal+delivery,cents(args.discount_cents));return{customer_name:String(args.customer_name||'Cliente').trim()||'Cliente',customer_phone:args.customer_phone?String(args.customer_phone):null,items:resolved,subtotal_cents:subtotal,delivery_cents:delivery,discount_cents:discount,total_cents:subtotal+delivery-discount,fulfillment_type:String(args.fulfillment_type||'pickup'),notes:args.notes?String(args.notes):null};}
async function createOrder(env:Env,tenantId:string,args:Dict,actorId:string){const preview=await prepareOrder(env,tenantId,args);const phone=preview.customer_phone?String(preview.customer_phone):null;let customerId:string|null=null;if(phone){const found=await env.DB.prepare('SELECT id FROM customers WHERE tenant_id=? AND phone=? LIMIT 1').bind(tenantId,phone).first<{id:string}>();customerId=found?.id||null;}if(!customerId){customerId=makeId('cus');await env.DB.prepare('INSERT INTO customers (id,tenant_id,name,phone) VALUES (?,?,?,?)').bind(customerId,tenantId,preview.customer_name,phone).run();}const orderId=makeId('ord'),publicCode=`NJ-${Date.now().toString(36).toUpperCase()}`;const statements:D1PreparedStatement[]=[env.DB.prepare(`INSERT INTO orders (id,tenant_id,customer_id,public_code,source,transaction_type,status,subtotal_cents,delivery_cents,discount_cents,total_cents,fulfillment_type,notes) VALUES (?,?,?,?,?,'order','new',?,?,?,?,?,?)`).bind(orderId,tenantId,customerId,publicCode,'agent',preview.subtotal_cents,preview.delivery_cents,preview.discount_cents,preview.total_cents,preview.fulfillment_type,preview.notes),env.DB.prepare(`INSERT INTO order_events (id,order_id,event_type,to_status,actor_type,actor_id,payload_json) VALUES (?,?,'order.created','new','agent',?,?)`).bind(makeId('evt'),orderId,actorId,JSON.stringify({source:'agent_gateway'}))];for(const item of preview.items as Array<any>)statements.push(env.DB.prepare(`INSERT INTO order_items (id,order_id,catalog_item_id,name,qty,unit_price_cents,total_cents,options_json) VALUES (?,?,?,?,?,?,?,'{}')`).bind(makeId('line'),orderId,item.catalog_item_id,item.name,item.qty,item.unit_price_cents,item.total_cents));await env.DB.batch(statements);return{id:orderId,public_code:publicCode,status:'new',total_cents:preview.total_cents};}
async function changeOrderStatus(env:Env,tenantId:string,args:Dict,actorId:string){const id=String(args.id||'').trim(),next=String(args.status||'').trim();if(!id||!next)throw new Error('Pedido e status são obrigatórios.');const current=await env.DB.prepare(`SELECT status,workflow_id FROM orders WHERE id=? AND tenant_id=? LIMIT 1`).bind(id,tenantId).first<{status:string;workflow_id:string|null}>();if(!current)throw new Error('Pedido não encontrado.');const valid=await env.DB.prepare(`SELECT ws.step_key FROM workflow_steps ws JOIN workflow_templates wt ON wt.id=ws.workflow_id WHERE wt.tenant_id=? AND ws.step_key=? AND (? IS NULL OR wt.id=?) LIMIT 1`).bind(tenantId,next,current.workflow_id,current.workflow_id).first();if(!valid)throw new Error('Etapa inválida para o workflow.');await env.DB.batch([env.DB.prepare(`UPDATE orders SET status=?,updated_at=datetime('now') WHERE id=? AND tenant_id=?`).bind(next,id,tenantId),env.DB.prepare(`INSERT INTO order_events (id,order_id,event_type,from_status,to_status,actor_type,actor_id) VALUES (?,?,?,?,?,'agent',?)`).bind(makeId('evt'),id,'order.status.changed',current.status,next,actorId)]);return{id,from:current.status,status:next};}
async function executeTool(env:Env,tenantId:string,tool:ToolName,args:Dict,actorId='agent'){if(tool==='catalog.search')return searchCatalog(env,tenantId,args);if(tool==='customer.lookup')return lookupCustomer(env,tenantId,args);if(tool==='order.lookup')return lookupOrder(env,tenantId,args);if(tool==='order.prepare')return prepareOrder(env,tenantId,args);if(tool==='order.create')return createOrder(env,tenantId,args,actorId);if(tool==='order.status.change')return changeOrderStatus(env,tenantId,args,actorId);throw new Error('Ferramenta não suportada.');}

export async function requestAgentTool(env:Env,tenantId:string,tool:string,args:Dict,context:{conversationId?:string|null;agentProfileId?:string|null;requestedBy?:string}={}){if(!READ_TOOLS.has(tool as ToolName)&&!WRITE_TOOLS.has(tool as ToolName))throw new Error('Ferramenta não permitida.');const id=makeId('tool');const risk=READ_TOOLS.has(tool as ToolName)?'read':'write';if(risk==='read'){try{const result=await executeTool(env,tenantId,tool as ToolName,args);await env.DB.prepare(`INSERT INTO agent_tool_calls (id,tenant_id,conversation_id,agent_profile_id,tool_name,risk_level,status,arguments_json,result_json,requested_by,executed_at) VALUES (?,?,?,?,?,?,'executed',?,?,?,datetime('now'))`).bind(id,tenantId,context.conversationId||null,context.agentProfileId||null,tool,risk,JSON.stringify(args),JSON.stringify(result),context.requestedBy||'agent').run();return{id,status:'executed',result};}catch(error){const msg=error instanceof Error?error.message:String(error);await env.DB.prepare(`INSERT INTO agent_tool_calls (id,tenant_id,conversation_id,agent_profile_id,tool_name,risk_level,status,arguments_json,error_text,requested_by,executed_at) VALUES (?,?,?,?,?,?,'failed',?,?,?,datetime('now'))`).bind(id,tenantId,context.conversationId||null,context.agentProfileId||null,tool,risk,JSON.stringify(args),msg,context.requestedBy||'agent').run();throw error;}}await env.DB.prepare(`INSERT INTO agent_tool_calls (id,tenant_id,conversation_id,agent_profile_id,tool_name,risk_level,status,arguments_json,requested_by) VALUES (?,?,?,?,?,?,'pending_approval',?,?)`).bind(id,tenantId,context.conversationId||null,context.agentProfileId||null,tool,risk,JSON.stringify(args),context.requestedBy||'agent').run();return{id,status:'pending_approval',requires_approval:true};}

export async function handleAgentTools(request:Request,env:Env,url:URL):Promise<Response|null>{if(!url.pathname.startsWith('/api/agent-tools'))return null;const actor=await authenticate(request,env);if(!actor)return json({error:'Sessão ausente ou expirada.'},401);const tenantId=await resolveTenant(request,env,actor);if(!tenantId)return json({error:'Selecione uma empresa para operar.'},409);const method=request.method.toUpperCase();
if(method==='GET'&&url.pathname==='/api/agent-tools'){const rows=await env.DB.prepare(`SELECT id,tool_name,risk_level,status,arguments_json,result_json,error_text,requested_by,approved_at,executed_at,created_at FROM agent_tool_calls WHERE tenant_id=? ORDER BY datetime(created_at) DESC LIMIT 100`).bind(tenantId).all();return json({data:rows.results||[]});}
if(method==='POST'&&url.pathname==='/api/agent-tools/execute'){const input=await body(request),tool=String(input.tool||''),args=(input.arguments&&typeof input.arguments==='object'?input.arguments:{}) as Dict;const result=await requestAgentTool(env,tenantId,tool,args,{conversationId:input.conversation_id?String(input.conversation_id):null,requestedBy:`user:${actor.actorId}`});await audit(env,actor,tenantId,'agent.tool.requested','agent_tool_call',result.id,{tool,status:result.status});return json({data:result},result.status==='pending_approval'?202:200);}
const approve=url.pathname.match(/^\/api\/agent-tools\/([^/]+)\/approve$/);if(method==='POST'&&approve){if(actor.role!=='admin'&&actor.role!=='super_admin')return json({error:'Apenas Admin pode aprovar ações de escrita.'},403);const call=await env.DB.prepare(`SELECT id,tool_name,status,arguments_json FROM agent_tool_calls WHERE id=? AND tenant_id=? LIMIT 1`).bind(approve[1],tenantId).first<{id:string;tool_name:ToolName;status:string;arguments_json:string}>();if(!call)return json({error:'Ação não encontrada.'},404);if(call.status!=='pending_approval')return json({error:'Ação não está pendente.'},409);let args:Dict={};try{args=JSON.parse(call.arguments_json||'{}')}catch{}try{const result=await executeTool(env,tenantId,call.tool_name,args,actor.actorId);await env.DB.prepare(`UPDATE agent_tool_calls SET status='executed',result_json=?,approved_by_user_id=?,approved_at=datetime('now'),executed_at=datetime('now') WHERE id=? AND tenant_id=?`).bind(JSON.stringify(result),actor.actorId,call.id,tenantId).run();await audit(env,actor,tenantId,'agent.tool.approved','agent_tool_call',call.id,{tool:call.tool_name});return json({data:{id:call.id,status:'executed',result}});}catch(error){const msg=error instanceof Error?error.message:String(error);await env.DB.prepare(`UPDATE agent_tool_calls SET status='failed',error_text=?,approved_by_user_id=?,approved_at=datetime('now'),executed_at=datetime('now') WHERE id=? AND tenant_id=?`).bind(msg,actor.actorId,call.id,tenantId).run();return json({error:msg},400);}}
return json({error:'Endpoint não encontrado.'},404);}
