/*
 * NegocIAJá! — desenvolvido pela SER Comunicação
 * CNPJ 23.296.513/0001-97
 * Todos os direitos reservados.
 */
import {Env,audit,authenticate,json} from './lib';

const ALLOWED_LOGO_TYPES=new Map([['image/png','png'],['image/jpeg','jpg'],['image/webp','webp']]);
const MAX_LOGO_BYTES=2*1024*1024,MAX_BACKGROUND_BYTES=5*1024*1024;
const COLOR_RE=/^#[0-9a-fA-F]{6}$/;
const text=(v:unknown,max:number)=>String(v||'').trim().slice(0,max);
async function putImage(request:Request,env:Env,keyPrefix:string,max:number){const type=(request.headers.get('content-type')||'').split(';')[0].trim().toLowerCase();const extension=ALLOWED_LOGO_TYPES.get(type);if(!extension)throw new Error('Formato não permitido. Use PNG, JPG ou WebP.');const bytes=await request.arrayBuffer();if(!bytes.byteLength||bytes.byteLength>max)throw new Error(`Arquivo deve ter no máximo ${Math.round(max/1024/1024)} MB.`);const key=`${keyPrefix}-${crypto.randomUUID()}.${extension}`;await env.FILES.put(key,bytes,{httpMetadata:{contentType:type,cacheControl:'private, max-age=3600'}});return{key,type,size:bytes.byteLength};}

export async function handleBranding(request:Request,env:Env,url:URL):Promise<Response|null>{
  if(!url.pathname.startsWith('/api/branding'))return null;
  const actor=await authenticate(request,env);if(!actor)return json({error:'Sessão ausente ou expirada.'},401);
  if(actor.actorType!=='tenant_user'||!actor.tenantId)return json({error:'Identidade disponível apenas para empresas autenticadas.'},403);
  const tenantId=actor.tenantId,method=request.method.toUpperCase();
  if(method==='GET'&&url.pathname==='/api/branding'){
    const row=await env.DB.prepare(`SELECT public_name,primary_color,secondary_color,logo_key,document_footer,document_notes,access_headline,access_message,access_show_brand,login_background_key,login_headline,login_message,login_button_label,storefront_enabled,storefront_headline,storefront_message FROM tenant_settings WHERE tenant_id=? LIMIT 1`).bind(tenantId).first<Record<string,unknown>>();
    return json({data:{public_name:row?.public_name||null,primary_color:row?.primary_color||'#169CFF',secondary_color:row?.secondary_color||'#0B2B7C',has_logo:Boolean(row?.logo_key),logo_url:row?.logo_key?'/api/branding/logo':null,document_footer:row?.document_footer||'',document_notes:row?.document_notes||'',access_headline:row?.access_headline||'',access_message:row?.access_message||'',access_show_brand:Number(row?.access_show_brand??1)!==0,login_headline:row?.login_headline||'',login_message:row?.login_message||'',login_button_label:row?.login_button_label||'',login_background_url:row?.login_background_key?'/api/branding/login-background':null,storefront_enabled:Number(row?.storefront_enabled??1)!==0,storefront_headline:row?.storefront_headline||'',storefront_message:row?.storefront_message||''}});
  }
  if(method==='PATCH'&&url.pathname==='/api/branding'){
    if(actor.role!=='admin')return json({error:'Apenas o administrador pode alterar a identidade.'},403);let input:Record<string,unknown>={};try{input=await request.json() as Record<string,unknown>;}catch{}
    const current=await env.DB.prepare(`SELECT * FROM tenant_settings WHERE tenant_id=?`).bind(tenantId).first<Record<string,unknown>>();const publicName=input.public_name===undefined?current?.public_name||null:text(input.public_name,120);const primary=input.primary_color===undefined?String(current?.primary_color||'#169CFF'):String(input.primary_color||'');const secondary=input.secondary_color===undefined?String(current?.secondary_color||'#0B2B7C'):String(input.secondary_color||'');if(!COLOR_RE.test(primary)||!COLOR_RE.test(secondary))return json({error:'Cor de identidade inválida.'},400);
    const footer=input.document_footer===undefined?current?.document_footer||null:text(input.document_footer,500),notes=input.document_notes===undefined?current?.document_notes||null:text(input.document_notes,1500),headline=input.access_headline===undefined?current?.access_headline||null:text(input.access_headline,140),message=input.access_message===undefined?current?.access_message||null:text(input.access_message,600),showBrand=input.access_show_brand===undefined?Number(current?.access_show_brand??1)!==0:Boolean(input.access_show_brand);const loginHeadline=input.login_headline===undefined?current?.login_headline||null:text(input.login_headline,140),loginMessage=input.login_message===undefined?current?.login_message||null:text(input.login_message,600),loginButton=input.login_button_label===undefined?current?.login_button_label||null:text(input.login_button_label,80),storeEnabled=input.storefront_enabled===undefined?Number(current?.storefront_enabled??1)!==0:Boolean(input.storefront_enabled),storeHeadline=input.storefront_headline===undefined?current?.storefront_headline||null:text(input.storefront_headline,160),storeMessage=input.storefront_message===undefined?current?.storefront_message||null:text(input.storefront_message,600);
    await env.DB.prepare(`UPDATE tenant_settings SET public_name=?,primary_color=?,secondary_color=?,document_footer=?,document_notes=?,access_headline=?,access_message=?,access_show_brand=?,login_headline=?,login_message=?,login_button_label=?,storefront_enabled=?,storefront_headline=?,storefront_message=? WHERE tenant_id=?`).bind(publicName,primary,secondary,footer,notes,headline,message,showBrand?1:0,loginHeadline,loginMessage,loginButton,storeEnabled?1:0,storeHeadline,storeMessage,tenantId).run();await audit(env,actor,tenantId,'branding.update','tenant',tenantId,{public_name:publicName,login:true,storefront:true});return json({data:{ok:true}});
  }
  if(method==='PUT'&&url.pathname==='/api/branding/logo'){if(actor.role!=='admin')return json({error:'Apenas o administrador pode alterar o logotipo.'},403);try{const upload=await putImage(request,env,`tenants/${tenantId}/branding/logo`,MAX_LOGO_BYTES);const old=await env.DB.prepare('SELECT logo_key FROM tenant_settings WHERE tenant_id=?').bind(tenantId).first<{logo_key:string|null}>();await env.DB.prepare('UPDATE tenant_settings SET logo_key=? WHERE tenant_id=?').bind(upload.key,tenantId).run();if(old?.logo_key)await env.FILES.delete(old.logo_key);await audit(env,actor,tenantId,'branding.logo.update','tenant',tenantId,{content_type:upload.type,size_bytes:upload.size});return json({data:{ok:true,logo_url:'/api/branding/logo'}});}catch(e){return json({error:e instanceof Error?e.message:'Falha no upload.'},400);}}
  if(method==='PUT'&&url.pathname==='/api/branding/login-background'){if(actor.role!=='admin')return json({error:'Apenas o administrador pode alterar o fundo do login.'},403);try{const upload=await putImage(request,env,`tenants/${tenantId}/branding/login-bg`,MAX_BACKGROUND_BYTES);const old=await env.DB.prepare('SELECT login_background_key FROM tenant_settings WHERE tenant_id=?').bind(tenantId).first<{login_background_key:string|null}>();await env.DB.prepare('UPDATE tenant_settings SET login_background_key=? WHERE tenant_id=?').bind(upload.key,tenantId).run();if(old?.login_background_key)await env.FILES.delete(old.login_background_key);await audit(env,actor,tenantId,'branding.login_background.update','tenant',tenantId,{size_bytes:upload.size});return json({data:{ok:true,login_background_url:'/api/branding/login-background'}});}catch(e){return json({error:e instanceof Error?e.message:'Falha no upload.'},400);}}
  if(method==='DELETE'&&url.pathname==='/api/branding/logo'){if(actor.role!=='admin')return json({error:'Apenas o administrador pode remover o logotipo.'},403);const row=await env.DB.prepare('SELECT logo_key FROM tenant_settings WHERE tenant_id=?').bind(tenantId).first<{logo_key:string|null}>();if(row?.logo_key)await env.FILES.delete(row.logo_key);await env.DB.prepare('UPDATE tenant_settings SET logo_key=NULL WHERE tenant_id=?').bind(tenantId).run();return json({data:{ok:true}});}
  if(method==='DELETE'&&url.pathname==='/api/branding/login-background'){if(actor.role!=='admin')return json({error:'Apenas o administrador pode remover o fundo do login.'},403);const row=await env.DB.prepare('SELECT login_background_key FROM tenant_settings WHERE tenant_id=?').bind(tenantId).first<{login_background_key:string|null}>();if(row?.login_background_key)await env.FILES.delete(row.login_background_key);await env.DB.prepare('UPDATE tenant_settings SET login_background_key=NULL WHERE tenant_id=?').bind(tenantId).run();return json({data:{ok:true}});}
  if(method==='GET'&&(url.pathname==='/api/branding/logo'||url.pathname==='/api/branding/login-background')){const field=url.pathname.endsWith('login-background')?'login_background_key':'logo_key';const row=await env.DB.prepare(`SELECT ${field} file_key FROM tenant_settings WHERE tenant_id=?`).bind(tenantId).first<{file_key:string|null}>();if(!row?.file_key)return json({error:'Arquivo não cadastrado.'},404);const object=await env.FILES.get(row.file_key);if(!object)return json({error:'Arquivo não encontrado.'},404);const headers=new Headers();object.writeHttpMetadata(headers);headers.set('cache-control','private, max-age=3600');headers.set('x-content-type-options','nosniff');return new Response(object.body,{headers});}
  return json({error:'Endpoint não encontrado.'},404);
}
