/*
 * NegocIAJá! — desenvolvido pela SER Comunicação
 * CNPJ 23.296.513/0001-97
 * Todos os direitos reservados.
 */
import {Env,authenticate,json,makeId,resolveTenant,sha256} from './lib';

const clean=(v:unknown,max=200)=>String(v??'').trim().slice(0,max);
async function tenantBySlug(env:Env,slug:string){return env.DB.prepare(`SELECT id FROM tenants WHERE slug=? AND status IN ('trial','active') LIMIT 1`).bind(slug).first<{id:string}>();}
async function commerceSession(env:Env,tenantId:string,request:Request){const token=clean(request.headers.get('x-commerce-token'),500);if(!token)return null;return env.DB.prepare(`SELECT id,customer_email,customer_phone FROM commerce_sessions WHERE tenant_id=? AND token_hash=? AND status='active' AND datetime(expires_at)>datetime('now') LIMIT 1`).bind(tenantId,await sha256(token)).first<any>();}

export async function handleCommercePreferences(request:Request,env:Env,url:URL):Promise<Response|null>{
  const pub=url.pathname.match(/^\/api\/shop\/([^/]+)\/preferences$/);if(pub){const tenant=await tenantBySlug(env,decodeURIComponent(pub[1]));if(!tenant)return json({error:'Loja indisponível.'},404);const s=await commerceSession(env,tenant.id,request);if(!s)return json({error:'Sessão da loja ausente ou expirada.'},401);if(request.method==='GET'){const row=await env.DB.prepare(`SELECT email_updates,whatsapp_updates,marketing_email,marketing_whatsapp,consented_at FROM commerce_preferences WHERE tenant_id=? AND session_id=?`).bind(tenant.id,s.id).first<any>();return json({data:{email_updates:Boolean(row?.email_updates),whatsapp_updates:Boolean(row?.whatsapp_updates),marketing_email:Boolean(row?.marketing_email),marketing_whatsapp:Boolean(row?.marketing_whatsapp),consented_at:row?.consented_at||null}});}if(request.method==='PUT'){let input:any={};try{input=await request.json()}catch{};const values=[Boolean(input.email_updates),Boolean(input.whatsapp_updates),Boolean(input.marketing_email),Boolean(input.marketing_whatsapp)];await env.DB.prepare(`INSERT INTO commerce_preferences (id,tenant_id,session_id,email_updates,whatsapp_updates,marketing_email,marketing_whatsapp,consent_source,consented_at) VALUES (?,?,?,?,?,?,?,'storefront',datetime('now')) ON CONFLICT(tenant_id,session_id) DO UPDATE SET email_updates=excluded.email_updates,whatsapp_updates=excluded.whatsapp_updates,marketing_email=excluded.marketing_email,marketing_whatsapp=excluded.marketing_whatsapp,consent_source='storefront',consented_at=datetime('now'),updated_at=datetime('now')`).bind(makeId('cpref'),tenant.id,s.id,...values.map(v=>v?1:0)).run();return json({data:{ok:true}});}return json({error:'Método não permitido.'},405);}
  if(url.pathname==='/api/commerce/recovery-candidates'){const actor=await authenticate(request,env);if(!actor)return json({error:'Sessão ausente ou expirada.'},401);const tenantId=await resolveTenant(request,env,actor);if(!tenantId)return json({error:'Selecione uma empresa.'},409);if(request.method!=='GET')return json({error:'Método não permitido.'},405);const rows=await env.DB.prepare(`SELECT c.id cart_id,c.session_id,c.updated_at,s.customer_name,s.customer_email,s.customer_phone,p.marketing_email,p.marketing_whatsapp,COUNT(ci.id) item_count,SUM(ci.qty*cat.price_cents) cart_value_cents FROM commerce_carts c JOIN commerce_sessions s ON s.id=c.session_id JOIN commerce_preferences p ON p.tenant_id=c.tenant_id AND p.session_id=c.session_id LEFT JOIN commerce_cart_items ci ON ci.cart_id=c.id LEFT JOIN catalog_items cat ON cat.id=ci.catalog_item_id WHERE c.tenant_id=? AND c.status='open' AND datetime(c.updated_at)<datetime('now','-30 minutes') AND (p.marketing_email=1 OR p.marketing_whatsapp=1) AND NOT EXISTS (SELECT 1 FROM commerce_outreach_log l WHERE l.tenant_id=c.tenant_id AND l.session_id=c.session_id AND l.outreach_type='cart_recovery' AND datetime(l.created_at)>datetime('now','-24 hours')) GROUP BY c.id HAVING COUNT(ci.id)>0 ORDER BY datetime(c.updated_at) ASC LIMIT 100`).bind(tenantId).all();return json({data:rows.results||[]});}
  return null;
}
