/*
 * NegocIAJá! — desenvolvido pela SER Comunicação
 * CNPJ 23.296.513/0001-97
 * Todos os direitos reservados.
 */
import {Env,json,makeId,sha256} from './lib';
import {createOrder} from './order-service';

const clean=(v:unknown,max=200)=>String(v??'').trim().slice(0,max);
async function tenantBySlug(env:Env,slug:string){return env.DB.prepare(`SELECT t.id,t.slug,t.name,t.status,s.public_name,s.primary_color,s.secondary_color,s.logo_key,s.storefront_enabled,s.storefront_headline,s.storefront_message FROM tenants t LEFT JOIN tenant_settings s ON s.tenant_id=t.id WHERE t.slug=? AND t.status IN ('trial','active') LIMIT 1`).bind(slug).first<any>();}
async function session(env:Env,tenantId:string,request:Request){const token=clean(request.headers.get('x-commerce-token'),500);if(!token)return null;const hash=await sha256(token);return env.DB.prepare(`SELECT id,customer_id,customer_name,customer_phone FROM commerce_sessions WHERE tenant_id=? AND token_hash=? AND status='active' AND datetime(expires_at)>datetime('now') LIMIT 1`).bind(tenantId,hash).first<any>();}
async function ensureCart(env:Env,tenantId:string,sessionId:string){let row=await env.DB.prepare(`SELECT id FROM commerce_carts WHERE tenant_id=? AND session_id=? AND status='open' LIMIT 1`).bind(tenantId,sessionId).first<{id:string}>();if(row)return row.id;const id=makeId('cart');await env.DB.prepare(`INSERT INTO commerce_carts (id,tenant_id,session_id) VALUES (?,?,?)`).bind(id,tenantId,sessionId).run();return id;}
async function cartView(env:Env,tenantId:string,sessionId:string){const cartId=await ensureCart(env,tenantId,sessionId);const rows=await env.DB.prepare(`SELECT ci.catalog_item_id,ci.qty,c.name,c.category,c.item_type,c.price_cents,c.stock_control,c.stock_qty,(c.price_cents*ci.qty) total_cents FROM commerce_cart_items ci JOIN catalog_items c ON c.id=ci.catalog_item_id WHERE ci.cart_id=? AND c.tenant_id=? AND c.active=1 ORDER BY ci.created_at`).bind(cartId,tenantId).all();const items=rows.results||[];const subtotal=items.reduce((sum:any,x:any)=>sum+Number(x.total_cents||0),0);return{cart_id:cartId,items,subtotal_cents:Math.round(subtotal),total_cents:Math.round(subtotal)};}

export async function handleCommerce(request:Request,env:Env,url:URL):Promise<Response|null>{
  const match=url.pathname.match(/^\/api\/shop\/([^/]+)(?:\/(.*))?$/);if(!match)return null;const slug=decodeURIComponent(match[1]),path=match[2]||'',method=request.method.toUpperCase();const tenant=await tenantBySlug(env,slug);if(!tenant||Number(tenant.storefront_enabled??1)===0)return json({error:'Loja indisponível.'},404);const tenantId=tenant.id;
  if(method==='GET'&&path==='storefront')return json({data:{slug:tenant.slug,name:tenant.public_name||tenant.name,headline:tenant.storefront_headline||'Compre, contrate ou peça novamente.',message:tenant.storefront_message||'Seu catálogo, seus pedidos e seu atendimento em um único fluxo.',primary_color:tenant.primary_color||'#169CFF',secondary_color:tenant.secondary_color||'#0B2B7C',logo_url:tenant.logo_key?`/api/shop/${encodeURIComponent(slug)}/logo`:null}});
  if(method==='GET'&&path==='logo'){if(!tenant.logo_key)return json({error:'Sem logotipo.'},404);const obj=await env.FILES.get(tenant.logo_key);if(!obj)return json({error:'Arquivo não encontrado.'},404);const h=new Headers();obj.writeHttpMetadata(h);h.set('cache-control','public, max-age=3600');h.set('x-content-type-options','nosniff');return new Response(obj.body,{headers:h});}
  if(method==='GET'&&path==='catalog'){const q=clean(url.searchParams.get('q'),120);const category=clean(url.searchParams.get('category'),120);let sql=`SELECT id,name,item_type,category,price_cents,stock_control,stock_qty FROM catalog_items WHERE tenant_id=? AND active=1`;const binds:any[]=[tenantId];if(q){sql+=` AND (name LIKE ? OR category LIKE ?)`;binds.push(`%${q}%`,`%${q}%`)}if(category){sql+=` AND category=?`;binds.push(category)}sql+=` ORDER BY category,name LIMIT 300`;const rows=await env.DB.prepare(sql).bind(...binds).all();return json({data:rows.results||[]});}
  if(method==='POST'&&path==='session'){const token=crypto.randomUUID()+crypto.randomUUID();const id=makeId('shop');await env.DB.prepare(`INSERT INTO commerce_sessions (id,tenant_id,token_hash,expires_at) VALUES (?,?,?,datetime('now','+30 days'))`).bind(id,tenantId,await sha256(token)).run();await ensureCart(env,tenantId,id);return json({data:{token,expires_in_days:30}},201);}
  const s=await session(env,tenantId,request);if(!s)return json({error:'Sessão da loja ausente ou expirada.'},401);
  if(method==='GET'&&path==='cart')return json({data:await cartView(env,tenantId,s.id)});
  if(method==='PUT'&&path==='cart'){let input:any={};try{input=await request.json()}catch{};const itemId=clean(input.catalog_item_id,120),qty=Number(input.qty);if(!itemId||!Number.isFinite(qty)||qty<0)return json({error:'Item/quantidade inválidos.'},400);const item=await env.DB.prepare(`SELECT id,stock_control,stock_qty FROM catalog_items WHERE id=? AND tenant_id=? AND active=1`).bind(itemId,tenantId).first<any>();if(!item)return json({error:'Item indisponível.'},404);if(item.stock_control&&qty>Number(item.stock_qty))return json({error:'Quantidade acima do estoque disponível.'},409);const cartId=await ensureCart(env,tenantId,s.id);if(qty===0)await env.DB.prepare(`DELETE FROM commerce_cart_items WHERE cart_id=? AND catalog_item_id=?`).bind(cartId,itemId).run();else await env.DB.prepare(`INSERT INTO commerce_cart_items (id,cart_id,catalog_item_id,qty) VALUES (?,?,?,?) ON CONFLICT(cart_id,catalog_item_id) DO UPDATE SET qty=excluded.qty,updated_at=datetime('now')`).bind(makeId('ci'),cartId,itemId,qty).run();return json({data:await cartView(env,tenantId,s.id)});}
  if(method==='POST'&&path==='checkout'){let input:any={};try{input=await request.json()}catch{};const view=await cartView(env,tenantId,s.id);if(!view.items.length)return json({error:'Carrinho vazio.'},400);const customerName=clean(input.customer_name,160),phone=clean(input.customer_phone,60);if(!customerName||!phone)return json({error:'Nome e WhatsApp são obrigatórios.'},400);const result=await createOrder(env,tenantId,{customer_name:customerName,customer_phone:phone,items:view.items.map((x:any)=>({catalog_item_id:x.catalog_item_id,qty:x.qty})),fulfillment_type:clean(input.fulfillment_type,40)||'pickup',notes:clean(input.notes,1200)},{type:'customer',id:s.id,source:'storefront'});await env.DB.batch([env.DB.prepare(`UPDATE commerce_sessions SET customer_name=?,customer_phone=?,updated_at=datetime('now') WHERE id=?`).bind(customerName,phone,s.id),env.DB.prepare(`UPDATE commerce_carts SET status='converted',updated_at=datetime('now') WHERE id=?`).bind(view.cart_id),env.DB.prepare(`INSERT INTO commerce_order_links (id,tenant_id,session_id,order_id) VALUES (?,?,?,?)`).bind(makeId('col'),tenantId,s.id,result.id)]);await ensureCart(env,tenantId,s.id);return json({data:result},201);}
  if(method==='GET'&&path==='orders'){const rows=await env.DB.prepare(`SELECT o.id,o.public_code,o.status,o.total_cents,o.fulfillment_type,o.created_at FROM commerce_order_links l JOIN orders o ON o.id=l.order_id WHERE l.tenant_id=? AND l.session_id=? ORDER BY o.created_at DESC LIMIT 100`).bind(tenantId,s.id).all();return json({data:rows.results||[]});}
  const repeat=path.match(/^orders\/([^/]+)\/repeat$/);if(method==='POST'&&repeat){const orderId=decodeURIComponent(repeat[1]);const linked=await env.DB.prepare(`SELECT o.id FROM commerce_order_links l JOIN orders o ON o.id=l.order_id WHERE l.tenant_id=? AND l.session_id=? AND o.id=? LIMIT 1`).bind(tenantId,s.id,orderId).first();if(!linked)return json({error:'Pedido não encontrado nesta sessão.'},404);const lines=await env.DB.prepare(`SELECT catalog_item_id,qty FROM order_items WHERE order_id=? AND catalog_item_id IS NOT NULL`).bind(orderId).all();const cartId=await ensureCart(env,tenantId,s.id);await env.DB.prepare(`DELETE FROM commerce_cart_items WHERE cart_id=?`).bind(cartId).run();for(const x of lines.results as any[])await env.DB.prepare(`INSERT OR REPLACE INTO commerce_cart_items (id,cart_id,catalog_item_id,qty) VALUES (?,?,?,?)`).bind(makeId('ci'),cartId,x.catalog_item_id,x.qty).run();return json({data:await cartView(env,tenantId,s.id)});}
  return json({error:'Endpoint não encontrado.'},404);
}
