/*
 * NegocIAJá! — desenvolvido pela SER Comunicação
 * CNPJ 23.296.513/0001-97
 * Todos os direitos reservados.
 */
import {Env,authenticate,escapeHtml,json,makeId,resolveTenant,responseTextLimited,sha256} from './lib';

const clean=(v:unknown,max=200)=>String(v??'').trim().slice(0,max);
async function tenantBySlug(env:Env,slug:string){return env.DB.prepare(`SELECT id,name,slug,status FROM tenants WHERE slug=? AND status IN ('trial','active') LIMIT 1`).bind(slug).first<any>();}
async function queueRecoveryEmail(env:Env,tenantId:string,email:string,code:string,storeName:string){const id=makeId('notify');await env.DB.prepare(`INSERT INTO notification_deliveries (id,tenant_id,channel,template_key,destination,status,payload_json) VALUES (?,?,'email','commerce_access_code',?,'pending',?)`).bind(id,tenantId,email,JSON.stringify({code,store_name:storeName})).run();if(!env.RESEND_API_KEY||!env.EMAIL_FROM)return false;const safeStore=escapeHtml(storeName),safeCode=escapeHtml(code);const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:env.EMAIL_FROM,to:[email],subject:`Código de acesso • ${storeName}`,html:`<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto"><h2>Recupere seus pedidos</h2><p>Use o código abaixo para acessar novamente seu histórico em ${safeStore}:</p><p style="font-size:32px;font-weight:800;letter-spacing:8px">${safeCode}</p><p>O código expira em 10 minutos e só pode ser usado uma vez.</p></div>`})});if(!r.ok){await env.DB.prepare(`UPDATE notification_deliveries SET status='failed',last_error=? WHERE id=?`).bind(await responseTextLimited(r,1000),id).run();return false}const out=await r.json() as{id?:string};await env.DB.prepare(`UPDATE notification_deliveries SET status='sent',provider_reference=?,sent_at=datetime('now') WHERE id=?`).bind(out.id||null,id).run();return true;}

export async function handleCommerceLifecycle(request:Request,env:Env,url:URL):Promise<Response|null>{
  const publicMatch=url.pathname.match(/^\/api\/shop\/([^/]+)\/recover\/(request|verify)$/);if(publicMatch){const slug=decodeURIComponent(publicMatch[1]),action=publicMatch[2],tenant=await tenantBySlug(env,slug);if(!tenant)return json({error:'Loja indisponível.'},404);if(request.method!=='POST')return json({error:'Método não permitido.'},405);let input:any={};try{input=await request.json()}catch{}const email=clean(input.email,180).toLowerCase();if(!email||!email.includes('@'))return json({error:'Informe um e-mail válido.'},400);
    if(action==='request'){const generic={ok:true,message:'Se houver histórico vinculado a este e-mail, um código será enviado.'};const s=await env.DB.prepare(`SELECT id FROM commerce_sessions WHERE tenant_id=? AND lower(customer_email)=? ORDER BY datetime(updated_at) DESC LIMIT 1`).bind(tenant.id,email).first<{id:string}>();if(!s)return json({data:generic});const recent=await env.DB.prepare(`SELECT created_at FROM commerce_access_codes WHERE tenant_id=? AND destination=? ORDER BY datetime(created_at) DESC LIMIT 1`).bind(tenant.id,email).first<{created_at:string}>();if(recent&&Date.now()-new Date(recent.created_at).getTime()<60_000)return json({data:generic});const n=crypto.getRandomValues(new Uint32Array(1))[0]%1000000,code=String(n).padStart(6,'0');await env.DB.prepare(`INSERT INTO commerce_access_codes (id,tenant_id,session_id,destination,code_hash,expires_at) VALUES (?,?,?,?,?,datetime('now','+10 minutes'))`).bind(makeId('cac'),tenant.id,s.id,email,await sha256(code)).run();await queueRecoveryEmail(env,tenant.id,email,code,tenant.name);return json({data:generic});}
    const code=clean(input.code,12);if(!/^\d{6}$/.test(code))return json({error:'Código inválido.'},400);const row=await env.DB.prepare(`SELECT id,session_id FROM commerce_access_codes WHERE tenant_id=? AND destination=? AND code_hash=? AND consumed_at IS NULL AND datetime(expires_at)>datetime('now') ORDER BY datetime(created_at) DESC LIMIT 1`).bind(tenant.id,email,await sha256(code)).first<{id:string;session_id:string}>();if(!row)return json({error:'Código inválido ou expirado.'},400);const token=(crypto.randomUUID()+crypto.randomUUID()).replaceAll('-','');await env.DB.batch([env.DB.prepare(`UPDATE commerce_access_codes SET consumed_at=datetime('now') WHERE id=? AND consumed_at IS NULL`).bind(row.id),env.DB.prepare(`UPDATE commerce_sessions SET token_hash=?,verified_at=datetime('now'),expires_at=datetime('now','+30 days'),status='active',updated_at=datetime('now') WHERE id=? AND tenant_id=?`).bind(await sha256(token),row.session_id,tenant.id)]);return json({data:{ok:true,token,expires_in_days:30}});
  }
  if(url.pathname==='/api/commerce/insights'){const actor=await authenticate(request,env);if(!actor)return json({error:'Sessão ausente ou expirada.'},401);const tenantId=await resolveTenant(request,env,actor);if(!tenantId)return json({error:'Selecione uma empresa.'},409);if(request.method!=='GET')return json({error:'Método não permitido.'},405);const [sessions,orders,repeats,abandoned,events]=await Promise.all([
    env.DB.prepare(`SELECT COUNT(*) total FROM commerce_sessions WHERE tenant_id=? AND datetime(created_at)>=datetime('now','-30 days')`).bind(tenantId).first<{total:number}>(),
    env.DB.prepare(`SELECT COUNT(DISTINCT session_id) sessions,COUNT(*) orders,SUM(o.total_cents) revenue FROM commerce_order_links l JOIN orders o ON o.id=l.order_id WHERE l.tenant_id=? AND datetime(l.created_at)>=datetime('now','-30 days')`).bind(tenantId).first<any>(),
    env.DB.prepare(`SELECT COUNT(*) total FROM commerce_events WHERE tenant_id=? AND event_type='order.repeated' AND datetime(created_at)>=datetime('now','-30 days')`).bind(tenantId).first<{total:number}>(),
    env.DB.prepare(`SELECT c.id,c.session_id,c.updated_at,s.customer_name,s.customer_phone,s.customer_email,COUNT(ci.id) item_count,SUM(ci.qty*cat.price_cents) cart_value_cents FROM commerce_carts c JOIN commerce_sessions s ON s.id=c.session_id LEFT JOIN commerce_cart_items ci ON ci.cart_id=c.id LEFT JOIN catalog_items cat ON cat.id=ci.catalog_item_id WHERE c.tenant_id=? AND c.status='open' AND datetime(c.updated_at)<datetime('now','-30 minutes') GROUP BY c.id HAVING COUNT(ci.id)>0 ORDER BY datetime(c.updated_at) DESC LIMIT 100`).bind(tenantId).all(),
    env.DB.prepare(`SELECT event_type,COUNT(*) total FROM commerce_events WHERE tenant_id=? AND datetime(created_at)>=datetime('now','-30 days') GROUP BY event_type ORDER BY total DESC`).bind(tenantId).all()
  ]);const totalSessions=Number(sessions?.total||0),buyerSessions=Number(orders?.sessions||0);return json({data:{period_days:30,sessions:totalSessions,buyer_sessions:buyerSessions,orders:Number(orders?.orders||0),revenue_cents:Number(orders?.revenue||0),conversion_rate:totalSessions?buyerSessions/totalSessions:0,repeats:Number(repeats?.total||0),abandoned_carts:abandoned.results||[],events:events.results||[]}});}
  return null;
}
