/*
 * NegocIAJá! — desenvolvido pela SER Comunicação
 * CNPJ 23.296.513/0001-97
 * Todos os direitos reservados.
 */
import {Env,authenticate,escapeHtml,json,makeId,resolveTenant,sha256} from './lib';
import {sendCommerceEmail,sendCommerceWhatsApp} from './commerce-dispatcher';

const clean=(v:unknown,max=500)=>String(v??'').trim().slice(0,max);
async function issueFeedbackToken(env:Env,tenantId:string,sessionId:string,orderId:string){const raw=`${crypto.randomUUID()}${crypto.randomUUID()}`.replaceAll('-','');await env.DB.prepare(`INSERT INTO commerce_feedback_tokens (id,tenant_id,session_id,order_id,token_hash,expires_at) VALUES (?,?,?,?,?,datetime('now','+7 days'))`).bind(makeId('fbt'),tenantId,sessionId,orderId,await sha256(raw)).run();return raw;}
export async function triggerPostSale(env:Env,tenantId:string,orderId:string,origin:string){const row=await env.DB.prepare(`SELECT l.session_id,s.customer_name,s.customer_email,s.customer_phone,p.email_updates,p.whatsapp_updates,o.public_code,o.status,t.slug,ws.post_sale_eligible FROM commerce_order_links l JOIN commerce_sessions s ON s.id=l.session_id JOIN orders o ON o.id=l.order_id JOIN tenants t ON t.id=l.tenant_id LEFT JOIN commerce_preferences p ON p.tenant_id=l.tenant_id AND p.session_id=l.session_id LEFT JOIN workflow_steps ws ON ws.workflow_id=o.workflow_id AND ws.step_key=o.status WHERE l.tenant_id=? AND l.order_id=? LIMIT 1`).bind(tenantId,orderId).first<any>();if(!row||Number(row.post_sale_eligible)!==1)return{eligible:false};const exists=await env.DB.prepare(`SELECT 1 ok FROM commerce_outreach_log WHERE tenant_id=? AND session_id=? AND outreach_type='post_sale_feedback' AND reference_id=? LIMIT 1`).bind(tenantId,row.session_id,orderId).first();if(exists)return{eligible:true,duplicate:true};const token=await issueFeedbackToken(env,tenantId,row.session_id,orderId),link=`${origin.replace(/\/$/,'')}/avaliar/${encodeURIComponent(row.slug)}?token=${encodeURIComponent(token)}`,payload={order_id:orderId,public_code:row.public_code,feedback_url:link};let email=false,whatsapp=false;if(Number(row.email_updates)===1&&row.customer_email){const r=await sendCommerceEmail(env,tenantId,row.session_id,'post_sale_feedback',row.customer_email,`Como foi sua experiência no pedido ${row.public_code}?`,`<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto"><h2>Obrigado pela preferência!</h2><p>Olá, ${escapeHtml(row.customer_name||'cliente')}. Seu pedido <strong>${escapeHtml(row.public_code)}</strong> foi concluído.</p><p>Conte em poucos segundos como foi sua experiência.</p><p><a href="${escapeHtml(link)}" style="display:inline-block;padding:14px 22px;background:#169CFF;color:#fff;text-decoration:none;border-radius:8px">Avaliar meu pedido</a></p></div>`,orderId,payload);email=Boolean(r.sent||r.queued)}if(Number(row.whatsapp_updates)===1&&row.customer_phone){const r=await sendCommerceWhatsApp(env,tenantId,row.session_id,'post_sale_feedback',row.customer_phone,`Pedido ${row.public_code} concluído ✅ Obrigado pela preferência! Como foi sua experiência? Avalie aqui: ${link}`,orderId,payload);whatsapp=Boolean(r.sent)}return{eligible:true,email,whatsapp};}

export async function handleCommercePostSale(request:Request,env:Env,url:URL):Promise<Response|null>{
  const publicMatch=url.pathname.match(/^\/api\/feedback\/([^/]+)$/);if(publicMatch){const raw=decodeURIComponent(publicMatch[1]);const hash=await sha256(raw);const token=await env.DB.prepare(`SELECT ft.id,ft.tenant_id,ft.session_id,ft.order_id,ft.expires_at,ft.consumed_at,o.public_code,t.slug,ts.public_name,t.name FROM commerce_feedback_tokens ft JOIN orders o ON o.id=ft.order_id JOIN tenants t ON t.id=ft.tenant_id LEFT JOIN tenant_settings ts ON ts.tenant_id=t.id WHERE ft.token_hash=? LIMIT 1`).bind(hash).first<any>();if(!token||token.consumed_at||Date.parse(token.expires_at)<Date.now())return json({error:'Link de avaliação inválido ou expirado.'},410);if(request.method==='GET')return json({data:{public_code:token.public_code,tenant_name:token.public_name||token.name,tenant_slug:token.slug}});if(request.method==='POST'){let input:any={};try{input=await request.json()}catch{};const rating=Number(input.rating),comment=clean(input.comment,1200);if(!Number.isInteger(rating)||rating<1||rating>5)return json({error:'Avaliação deve ser de 1 a 5.'},400);await env.DB.batch([env.DB.prepare(`INSERT INTO commerce_feedback (id,tenant_id,session_id,order_id,rating,comment) VALUES (?,?,?,?,?,?) ON CONFLICT(tenant_id,session_id,order_id) DO UPDATE SET rating=excluded.rating,comment=excluded.comment`).bind(makeId('fb'),token.tenant_id,token.session_id,token.order_id,rating,comment||null),env.DB.prepare(`UPDATE commerce_feedback_tokens SET consumed_at=datetime('now') WHERE id=? AND consumed_at IS NULL`).bind(token.id)]);return json({data:{ok:true}});}return json({error:'Método não permitido.'},405);}
  if(url.pathname==='/api/commerce/feedback'){const actor=await authenticate(request,env);if(!actor)return json({error:'Sessão ausente.'},401);const tenantId=await resolveTenant(request,env,actor);if(!tenantId)return json({error:'Selecione uma empresa.'},409);if(request.method!=='GET')return json({error:'Método não permitido.'},405);const [summary,recent]=await Promise.all([env.DB.prepare(`SELECT COUNT(*) total,ROUND(AVG(rating),2) average_rating,SUM(CASE WHEN rating>=4 THEN 1 ELSE 0 END) positive,SUM(CASE WHEN rating<=2 THEN 1 ELSE 0 END) critical FROM commerce_feedback WHERE tenant_id=?`).bind(tenantId).first(),env.DB.prepare(`SELECT f.rating,f.comment,f.created_at,o.public_code,c.name customer_name FROM commerce_feedback f JOIN orders o ON o.id=f.order_id LEFT JOIN customers c ON c.id=o.customer_id WHERE f.tenant_id=? ORDER BY f.created_at DESC LIMIT 50`).bind(tenantId).all()]);return json({data:{summary,recent:recent.results||[]}});}
  return null;
}
