/*
 * NegocIAJá! — desenvolvido pela SER Comunicação
 * CNPJ 23.296.513/0001-97
 * Todos os direitos reservados.
 */
import {Env,audit,authenticate,body,json,makeId,resolveTenant,sha256} from './lib';

const MAX_MEDIA_BYTES=10*1024*1024;
const base64Bytes=(value:string)=>Uint8Array.from(atob(value.replace(/^data:[^,]+,/,'')),c=>c.charCodeAt(0));
const clean=(v:unknown,max=500)=>String(v||'').trim().slice(0,max);

export async function handleEvolution(request:Request,env:Env,url:URL):Promise<Response|null>{
  const method=request.method.toUpperCase();
  if(url.pathname==='/api/channels/evolution'){
    const actor=await authenticate(request,env);if(!actor)return json({error:'Sessão ausente ou expirada.'},401);const tenantId=await resolveTenant(request,env,actor);if(!tenantId)return json({error:'Selecione uma empresa para operar.'},409);if(actor.role!=='admin'&&actor.role!=='super_admin')return json({error:'Sem permissão para configurar canais.'},403);
    if(method==='GET'){const rows=await env.DB.prepare(`SELECT id,instance_name,status,created_at,updated_at FROM channel_connections WHERE tenant_id=? AND provider='evolution' ORDER BY created_at DESC`).bind(tenantId).all();return json({data:rows.results||[]});}
    if(method==='POST'){const input=await body(request);const instance=clean(input.instance_name,120);if(!instance)return json({error:'Informe o nome da instância Evolution.'},400);const raw=`${crypto.randomUUID()}${crypto.randomUUID()}`.replaceAll('-','');const hash=await sha256(raw);const id=makeId('channel');await env.DB.prepare(`INSERT INTO channel_connections (id,tenant_id,provider,channel,instance_name,webhook_token_hash,status) VALUES (?,?,'evolution','whatsapp',?,?,'active') ON CONFLICT(tenant_id,provider,instance_name) DO UPDATE SET webhook_token_hash=excluded.webhook_token_hash,status='active',updated_at=datetime('now')`).bind(id,tenantId,instance,hash).run();await audit(env,actor,tenantId,'channel.evolution.configured','channel',instance);return json({data:{instance_name:instance,webhook_url:`${url.origin}/webhooks/evolution/${encodeURIComponent(instance)}`,webhook_header:{'x-negociaja-webhook-token':raw},events:['MESSAGES_UPSERT','MESSAGES_UPDATE','CONNECTION_UPDATE'],base64:true,note:'O token é exibido apenas nesta resposta. Configure-o no header do webhook da Evolution.'}},201);}
    return json({error:'Método não permitido.'},405);
  }

  const match=url.pathname.match(/^\/webhooks\/evolution\/([^/]+)$/);if(!match)return null;if(method!=='POST')return json({error:'Método não permitido.'},405);
  const instance=decodeURIComponent(match[1]);const connection=await env.DB.prepare(`SELECT id,tenant_id,webhook_token_hash,status FROM channel_connections WHERE provider='evolution' AND instance_name=? LIMIT 1`).bind(instance).first<{id:string;tenant_id:string;webhook_token_hash:string;status:string}>();if(!connection||connection.status!=='active')return json({error:'Canal não encontrado.'},404);const supplied=request.headers.get('x-negociaja-webhook-token')||'';if(!supplied||await sha256(supplied)!==connection.webhook_token_hash)return json({error:'Webhook não autorizado.'},401);
  let payload:Record<string,any>;try{payload=await request.json() as Record<string,any>;}catch{return json({error:'JSON inválido.'},400);}const event=clean(payload.event||payload.type,80).toUpperCase();if(event&&event!=='MESSAGES_UPSERT'&&event!=='MESSAGES.UPDATE'&&event!=='MESSAGES_UPDATE'&&event!=='CONNECTION_UPDATE')return json({data:{ignored:true,event}});
  if(event==='CONNECTION_UPDATE')return json({data:{ok:true,event}});
  const data=payload.data||payload;const key=data.key||{};if(key.fromMe===true)return json({data:{ignored:true,reason:'outbound_echo'}});const remoteJid=clean(key.remoteJid||data.remoteJid||data.sender,220);const externalId=clean(key.id||data.id||data.messageId,220);if(!remoteJid)return json({error:'Remetente não identificado.'},400);if(externalId){const exists=await env.DB.prepare(`SELECT id FROM conversation_messages WHERE tenant_id=? AND external_message_id=? LIMIT 1`).bind(connection.tenant_id,externalId).first();if(exists)return json({data:{ok:true,duplicate:true}});}
  const msg=data.message||{};const text=clean(msg.conversation||msg.extendedTextMessage?.text||msg.imageMessage?.caption||msg.videoMessage?.caption||data.body||'',8000);let type='text';let mime='';if(msg.audioMessage){type='audio';mime=clean(msg.audioMessage.mimetype,120);}else if(msg.imageMessage){type='image';mime=clean(msg.imageMessage.mimetype,120);}else if(msg.videoMessage){type='video';mime=clean(msg.videoMessage.mimetype,120);}else if(msg.documentMessage){type='document';mime=clean(msg.documentMessage.mimetype,120);}const customerName=clean(data.pushName||payload.senderName||remoteJid.split('@')[0],120);
  let conversation=await env.DB.prepare(`SELECT id FROM conversations WHERE tenant_id=? AND channel='whatsapp' AND external_thread_id=? LIMIT 1`).bind(connection.tenant_id,remoteJid).first<{id:string}>();const conversationId=conversation?.id||makeId('conv');if(!conversation)await env.DB.prepare(`INSERT INTO conversations (id,tenant_id,channel,external_thread_id,customer_name,customer_address,status,mode,last_message_at) VALUES (?,?,'whatsapp',?,?,?,'open','ai',datetime('now'))`).bind(conversationId,connection.tenant_id,remoteJid,customerName,remoteJid).run();else await env.DB.prepare(`UPDATE conversations SET customer_name=COALESCE(NULLIF(?,''),customer_name),status='open',last_message_at=datetime('now'),updated_at=datetime('now') WHERE id=? AND tenant_id=?`).bind(customerName,conversationId,connection.tenant_id).run();
  const messageId=makeId('msg');let mediaKey:string|null=null;const base64=clean(data.base64||payload.base64||msg.base64,20_000_000);if(base64&&type!=='text'){try{const bytes=base64Bytes(base64);if(bytes.byteLength<=MAX_MEDIA_BYTES){mediaKey=`tenants/${connection.tenant_id}/conversations/${conversationId}/${messageId}`;await env.FILES.put(mediaKey,bytes,{httpMetadata:{contentType:mime||'application/octet-stream',cacheControl:'private, max-age=3600'}});}}catch{}}
  await env.DB.batch([env.DB.prepare(`INSERT INTO conversation_messages (id,tenant_id,conversation_id,direction,sender_type,message_type,text_content,media_key,external_message_id,metadata_json) VALUES (?,?,?,'inbound','customer',?,?,?,?,?)`).bind(messageId,connection.tenant_id,conversationId,type,text||null,mediaKey,externalId||null,JSON.stringify({provider:'evolution',instance,event,mime})),env.DB.prepare(`INSERT INTO conversation_events (id,tenant_id,conversation_id,event_type,actor_type,payload_json) VALUES (?,?,?,'message.received','provider',?)`).bind(makeId('cevt'),connection.tenant_id,conversationId,JSON.stringify({provider:'evolution',instance,external_message_id:externalId||null}))]);
  return json({data:{ok:true,conversation_id:conversationId,message_id:messageId,message_type:type,media_stored:Boolean(mediaKey)}});
}
