import dispatch from './hml-dispatch';

interface Env{DB:D1Database;FILES:R2Bucket;ASSETS:Fetcher;APP_ENVIRONMENT:string;DEFAULT_TENANT_ID:string;ACCESS_TEAM_DOMAIN:string;ACCESS_AUD:string;HML_USERNAME?:string;HML_PASSWORD?:string;RESEND_API_KEY?:string;RESEND_FROM_EMAIL?:string;MERCADOPAGO_ACCESS_TOKEN?:string;MERCADOPAGO_WEBHOOK_SECRET?:string;OUTBOX_SERVICE_TOKEN?:string;HML_RATE_LIMIT_PER_MINUTE?:string}
type Session={tenant_id?:string;email?:string;role?:string;global_role?:string};type Dict=Record<string,unknown>;
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const id=(p:string)=>`${p}_${crypto.randomUUID()}`;const clean=(v:unknown,max=300)=>String(v??'').trim().slice(0,max);
const canPrivacy=(s:Session)=>s.global_role==='super_admin'||['owner','admin'].includes(String(s.role||''));
async function sessionFor(request:Request,env:Env){const r=await dispatch.fetch(new Request(new URL('/api/session',request.url).toString(),{method:'GET',headers:request.headers}),env);if(!r.ok)return{response:r};const p=await r.clone().json().catch(()=>({})) as {data?:Session};return{session:p.data||{}}}
async function body(request:Request):Promise<Dict>{const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new Response(JSON.stringify({error:'Origem não autorizada.'}),{status:403,headers:{'content-type':'application/json'}});if(!(request.headers.get('content-type')||'').toLowerCase().startsWith('application/json'))throw new Response(JSON.stringify({error:'Envie application/json.'}),{status:415,headers:{'content-type':'application/json'}});const raw=await request.text();if(raw.length>65536)throw new Response(JSON.stringify({error:'Corpo muito grande.'}),{status:413,headers:{'content-type':'application/json'}});try{const x=JSON.parse(raw||'{}');if(!x||typeof x!=='object'||Array.isArray(x))throw new Error();return x as Dict}catch{throw new Response(JSON.stringify({error:'JSON inválido.'}),{status:400,headers:{'content-type':'application/json'}})}}
function routeGroup(path:string){const p=path.split('/').filter(Boolean);return '/'+p.slice(0,3).join('/');}
async function rateLimit(env:Env,tenantId:string,request:Request){const method=request.method.toUpperCase();if(!['POST','PUT','PATCH','DELETE'].includes(method))return null;const limit=Math.max(20,Math.min(1000,Number(env.HML_RATE_LIMIT_PER_MINUTE)||120));const now=new Date();const windowStart=now.toISOString().slice(0,16);const scope=`${tenantId}:${method}:${routeGroup(new URL(request.url).pathname)}`;await env.DB.prepare(`INSERT INTO rate_limit_windows (scope_key,window_start,request_count,updated_at) VALUES (?,?,1,datetime('now')) ON CONFLICT(scope_key,window_start) DO UPDATE SET request_count=request_count+1,updated_at=datetime('now')`).bind(scope,windowStart).run();const row=await env.DB.prepare(`SELECT request_count FROM rate_limit_windows WHERE scope_key=? AND window_start=?`).bind(scope,windowStart).first<{request_count:number}>();const count=Number(row?.request_count||0);if(Math.random()<0.02)await env.DB.prepare(`DELETE FROM rate_limit_windows WHERE updated_at<datetime('now','-2 hour')`).run();if(count>limit)return new Response(JSON.stringify({error:'Muitas requisições. Tente novamente em instantes.',code:'rate_limited'}),{status:429,headers:{'content-type':'application/json; charset=utf-8','retry-after':'60','x-ratelimit-limit':String(limit),'x-ratelimit-remaining':'0','cache-control':'no-store'}});return null}
async function collectExport(env:Env,tenantId:string){const q=async(sql:string)=>((await env.DB.prepare(sql).bind(tenantId).all()).results);const [tenant,settings,business,branding,customers,catalog,orders,orderItems,conversations,messages,documents,receivables,inventory,audit]=await Promise.all([
 env.DB.prepare(`SELECT id,slug,name,segment,status,created_at FROM tenants WHERE id=?`).bind(tenantId).first(),
 env.DB.prepare(`SELECT * FROM tenant_settings WHERE tenant_id=?`).bind(tenantId).first(),env.DB.prepare(`SELECT * FROM tenant_business_profile WHERE tenant_id=?`).bind(tenantId).first(),env.DB.prepare(`SELECT * FROM tenant_branding WHERE tenant_id=?`).bind(tenantId).first(),
 q(`SELECT * FROM customers WHERE tenant_id=?`),q(`SELECT * FROM catalog_items WHERE tenant_id=?`),q(`SELECT * FROM orders WHERE tenant_id=?`),q(`SELECT oi.* FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.tenant_id=?`),q(`SELECT * FROM conversations WHERE tenant_id=?`),q(`SELECT m.* FROM messages m JOIN conversations c ON c.id=m.conversation_id WHERE c.tenant_id=?`),q(`SELECT id,document_type,document_number,entity_type,entity_id,status,file_key,created_at FROM generated_documents WHERE tenant_id=?`),q(`SELECT * FROM receivables WHERE tenant_id=?`),q(`SELECT * FROM inventory_movements WHERE tenant_id=?`),q(`SELECT * FROM audit_logs WHERE tenant_id=? ORDER BY created_at DESC LIMIT 5000`)
]);return{exported_at:new Date().toISOString(),tenant,settings,business,branding,customers,catalog,orders,order_items:orderItems,conversations,messages,documents,receivables,inventory_movements:inventory,audit_logs:audit}}
async function createExport(env:Env,tenantId:string,s:Session){if(!canPrivacy(s))return json({error:'Seu perfil não pode exportar dados da empresa.'},403);const requestId=id('privacy');const payload=await collectExport(env,tenantId);const bytes=new TextEncoder().encode(JSON.stringify(payload));const key=`tenants/${tenantId}/privacy/${requestId}.json`;await env.FILES.put(key,bytes,{httpMetadata:{contentType:'application/json'},customMetadata:{tenant_id:tenantId,privacy_request_id:requestId}});await env.DB.batch([env.DB.prepare(`INSERT INTO privacy_requests (id,tenant_id,request_type,status,requested_by,export_key,export_size,completed_at) VALUES (?,?,'export','completed',?,?,?,datetime('now'))`).bind(requestId,tenantId,s.email||null,key,bytes.byteLength),env.DB.prepare(`INSERT INTO audit_logs (id,tenant_id,actor_type,actor_id,action,entity_type,entity_id,payload_json) VALUES (?,?,'operator',?,'privacy.export.created','privacy_request',?,?)`).bind(id('audit'),tenantId,s.email||null,requestId,JSON.stringify({size:bytes.byteLength}))]);return json({data:{id:requestId,status:'completed',download_url:`/api/privacy/exports/${encodeURIComponent(requestId)}`,size:bytes.byteLength}},201)}
async function serveExport(env:Env,tenantId:string,requestId:string){const row=await env.DB.prepare(`SELECT export_key FROM privacy_requests WHERE id=? AND tenant_id=? AND request_type='export' AND status='completed'`).bind(requestId,tenantId).first<{export_key:string}>();if(!row?.export_key)return json({error:'Exportação não encontrada.'},404);const obj=await env.FILES.get(row.export_key);if(!obj)return json({error:'Arquivo de exportação indisponível.'},404);return new Response(obj.body,{headers:{'content-type':'application/json; charset=utf-8','content-disposition':`attachment; filename="negociaja-${tenantId}-dados.json"`,'cache-control':'private, no-store','x-content-type-options':'nosniff'}})}
async function requestDeletion(request:Request,env:Env,tenantId:string,s:Session){if(!canPrivacy(s))return json({error:'Seu perfil não pode solicitar exclusão.'},403);const x=await body(request);if(clean(x.confirm,40)!=='EXCLUIR DADOS')return json({error:'Confirmação inválida. Digite EXCLUIR DADOS.'},400);const existing=await env.DB.prepare(`SELECT id,execute_after FROM privacy_requests WHERE tenant_id=? AND request_type='deletion' AND status='requested' ORDER BY created_at DESC LIMIT 1`).bind(tenantId).first();if(existing)return json({data:existing});const requestId=id('privacy');await env.DB.batch([env.DB.prepare(`INSERT INTO privacy_requests (id,tenant_id,request_type,status,requested_by,execute_after,metadata_json) VALUES (?,?,'deletion','requested',?,datetime('now','+7 day'),?)`).bind(requestId,tenantId,s.email||null,JSON.stringify({cooling_off_days:7})),env.DB.prepare(`INSERT INTO audit_logs (id,tenant_id,actor_type,actor_id,action,entity_type,entity_id,payload_json) VALUES (?,?,'operator',?,'privacy.deletion.requested','privacy_request',?,'{}')`).bind(id('audit'),tenantId,s.email||null,requestId)]);const row=await env.DB.prepare(`SELECT id,status,execute_after FROM privacy_requests WHERE id=?`).bind(requestId).first();return json({data:row},201)}
async function listPrivacy(env:Env,tenantId:string){const [requests,policy]=await Promise.all([env.DB.prepare(`SELECT id,request_type,status,requested_by,export_size,execute_after,completed_at,cancelled_at,created_at FROM privacy_requests WHERE tenant_id=? ORDER BY created_at DESC LIMIT 50`).bind(tenantId).all(),env.DB.prepare(`SELECT audit_days,conversation_days,notification_days,failed_delivery_days,updated_at FROM tenant_retention_policies WHERE tenant_id=?`).bind(tenantId).first()]);return{requests:requests.results,retention:policy||null}}
async function cancelDeletion(env:Env,tenantId:string,s:Session,requestId:string){if(!canPrivacy(s))return json({error:'Seu perfil não pode cancelar exclusão.'},403);const row=await env.DB.prepare(`SELECT id,status FROM privacy_requests WHERE id=? AND tenant_id=? AND request_type='deletion'`).bind(requestId,tenantId).first<{id:string;status:string}>();if(!row)return json({error:'Solicitação não encontrada.'},404);if(row.status!=='requested')return json({error:'Solicitação não pode mais ser cancelada.'},409);await env.DB.prepare(`UPDATE privacy_requests SET status='cancelled',cancelled_at=datetime('now'),updated_at=datetime('now') WHERE id=? AND tenant_id=?`).bind(requestId,tenantId).run();return json({data:{id:requestId,status:'cancelled'}})}
export default{async fetch(request:Request,env:Env):Promise<Response>{try{const u=new URL(request.url),method=request.method.toUpperCase(),exportMatch=u.pathname.match(/^\/api\/privacy\/exports\/([^/]+)$/),cancelMatch=u.pathname.match(/^\/api\/privacy\/deletion\/([^/]+)\/cancel$/);const privacy=u.pathname==='/api/privacy'||u.pathname==='/api/privacy/export'||u.pathname==='/api/privacy/deletion'||Boolean(exportMatch||cancelMatch);const service=u.pathname.startsWith('/api/integrations/outbox/');if(service)return dispatch.fetch(request,env);const auth=await sessionFor(request,env);if(auth.response)return auth.response;const s=auth.session||{},tenantId=s.tenant_id||env.DEFAULT_TENANT_ID;if(!tenantId)return json({error:'Tenant indisponível.'},403);const limited=await rateLimit(env,tenantId,request);if(limited)return limited;if(!privacy)return dispatch.fetch(request,env);if(u.pathname==='/api/privacy'&&method==='GET')return json({data:await listPrivacy(env,tenantId)});if(u.pathname==='/api/privacy/export'&&method==='POST')return createExport(env,tenantId,s);if(exportMatch&&method==='GET'){if(!canPrivacy(s))return json({error:'Sem permissão.'},403);return serveExport(env,tenantId,decodeURIComponent(exportMatch[1]))}if(u.pathname==='/api/privacy/deletion'&&method==='POST')return requestDeletion(request,env,tenantId,s);if(cancelMatch&&method==='POST')return cancelDeletion(env,tenantId,s,decodeURIComponent(cancelMatch[1]));return json({error:'Método não permitido.'},405)}catch(e){if(e instanceof Response)return e;console.error('HML security/privacy error',e);return json({error:'Erro interno de segurança/privacidade.'},500)}}};
