import health from './hml-health';
import core from './hml-dispatch-core';

interface Env{DB:D1Database;FILES:R2Bucket;ASSETS:Fetcher;APP_ENVIRONMENT:string;DEFAULT_TENANT_ID:string;ACCESS_TEAM_DOMAIN:string;ACCESS_AUD:string;HML_USERNAME?:string;HML_PASSWORD?:string}
type Session={tenant_id?:string;email?:string;role?:string;global_role?:string};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const canManage=(s:Session)=>s.global_role==='super_admin'||['owner','admin','manager'].includes(String(s.role||''));
async function sessionFor(request:Request,env:Env){const r=await core.fetch(new Request(new URL('/api/session',request.url).toString(),{method:'GET',headers:request.headers}),env);if(!r.ok)return{response:r};const p=await r.clone().json().catch(()=>({})) as {data?:Session};return{session:p.data||{}}}
function keyFor(tenantId:string,itemId:string){return `tenants/${tenantId}/catalog/${itemId}/main`}
async function catalogImage(request:Request,env:Env,itemId:string){const auth=await sessionFor(request,env);if(auth.response)return auth.response;const s=auth.session||{},tenantId=s.tenant_id||env.DEFAULT_TENANT_ID;if(!tenantId)return json({error:'Tenant indisponível.'},403);const item=await env.DB.prepare('SELECT id FROM catalog_items WHERE id=? AND tenant_id=?').bind(itemId,tenantId).first();if(!item)return json({error:'Item não encontrado.'},404);const key=keyFor(tenantId,itemId),method=request.method.toUpperCase();if(method==='GET'){const obj=await env.FILES.get(key);if(!obj)return new Response(null,{status:404});const headers=new Headers();obj.writeHttpMetadata(headers);headers.set('cache-control','private, max-age=300');headers.set('x-content-type-options','nosniff');return new Response(obj.body,{headers})}if(method==='DELETE'){if(!canManage(s))return json({error:'Sem permissão para remover imagem.'},403);await env.FILES.delete(key);return json({data:{removed:true}})}if(method!=='PUT')return json({error:'Método não permitido.'},405);if(!canManage(s))return json({error:'Sem permissão para alterar imagem.'},403);const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return json({error:'Origem não autorizada.'},403);const mime=(request.headers.get('content-type')||'').split(';')[0].trim().toLowerCase();if(!['image/png','image/jpeg','image/webp'].includes(mime))return json({error:'Use PNG, JPG ou WebP.'},415);const bytes=await request.arrayBuffer();if(bytes.byteLength<16)return json({error:'Arquivo de imagem inválido.'},400);if(bytes.byteLength>5*1024*1024)return json({error:'Imagem maior que 5 MB.'},413);await env.FILES.put(key,bytes,{httpMetadata:{contentType:mime,cacheControl:'private, max-age=300'},customMetadata:{tenant_id:tenantId,catalog_item_id:itemId,uploaded_by:s.email||'operator'}});await env.DB.prepare("INSERT INTO audit_logs (id,tenant_id,actor_type,actor_id,action,entity_type,entity_id,payload_json) VALUES (?,?, 'operator',?,'catalog.image.updated','catalog_item',?,?)").bind(`audit_${crypto.randomUUID()}`,tenantId,s.email||null,itemId,JSON.stringify({mime,size:bytes.byteLength,key})).run();return json({data:{item_id:itemId,image_url:`/api/catalog/${encodeURIComponent(itemId)}/image`,mime,size:bytes.byteLength}},201)}
export default{async fetch(request:Request,env:Env):Promise<Response>{try{const u=new URL(request.url);const image=u.pathname.match(/^\/api\/catalog\/([^/]+)\/image$/);if(image)return catalogImage(request,env,decodeURIComponent(image[1]));if(u.pathname.startsWith('/api/ops/integration-health')||u.pathname.startsWith('/api/privacy'))return health.fetch(request,env);return core.fetch(request,env)}catch(e){if(e instanceof Response)return e;console.error('HML stable gateway error',e);return json({error:'Erro interno do gateway HML.'},500)}}};
