import security from './hml-security';

interface Env{DB:D1Database;FILES:R2Bucket;ASSETS:Fetcher;APP_ENVIRONMENT:string;DEFAULT_TENANT_ID:string;ACCESS_TEAM_DOMAIN:string;ACCESS_AUD:string;HML_USERNAME?:string;HML_PASSWORD?:string;OUTBOX_SERVICE_TOKEN?:string}
type Session={tenant_id?:string;email?:string;role?:string;global_role?:string};type Dict=Record<string,unknown>;
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const id=(p:string)=>`${p}_${crypto.randomUUID()}`;const clean=(v:unknown,max=500)=>String(v??'').trim().slice(0,max);
const allowedProviders=new Set(['evolution','n8n','openai','telegram','resend','mercadopago','outbox','cloudflare']);
async function sessionFor(request:Request,env:Env){const r=await security.fetch(new Request(new URL('/api/session',request.url).toString(),{method:'GET',headers:request.headers}),env);if(!r.ok)return{response:r};const p=await r.clone().json().catch(()=>({})) as {data?:Session};return{session:p.data||{}}}
function canViewPlatform(s:Session){return s.global_role==='super_admin'||['owner','admin','manager'].includes(String(s.role||''))}
async function body(request:Request):Promise<Dict>{const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new Response(JSON.stringify({error:'Origem não autorizada.'}),{status:403,headers:{'content-type':'application/json'}});if(!(request.headers.get('content-type')||'').startsWith('application/json'))throw new Response(JSON.stringify({error:'Envie application/json.'}),{status:415,headers:{'content-type':'application/json'}});const raw=await request.text();if(raw.length>32768)throw new Response(JSON.stringify({error:'Corpo muito grande.'}),{status:413,headers:{'content-type':'application/json'}});try{const x=JSON.parse(raw||'{}');if(!x||typeof x!=='object'||Array.isArray(x))throw new Error();return x as Dict}catch{throw new Response(JSON.stringify({error:'JSON inválido.'}),{status:400,headers:{'content-type':'application/json'}})}}
async function recordHealth(request:Request,env:Env,tenantId:string,s:Session){if(!canViewPlatform(s))return json({error:'Seu perfil não pode registrar diagnóstico.'},403);const x=await body(request);const provider=clean(x.provider,40).toLowerCase(),status=clean(x.status,20).toLowerCase();if(!allowedProviders.has(provider))return json({error:'Provider inválido.'},400);if(!['healthy','degraded','down','disconnected','unknown'].includes(status))return json({error:'Status inválido.'},400);const eventId=id('health');await env.DB.prepare(`INSERT INTO integration_health_events (id,tenant_id,provider,component,status,latency_ms,message,metadata_json) VALUES (?,?,?,?,?,?,?,?)`).bind(eventId,tenantId,provider,clean(x.component,80)||null,status,Number.isFinite(Number(x.latency_ms))?Math.max(0,Math.round(Number(x.latency_ms))):null,clean(x.message,1000)||null,JSON.stringify(x.metadata&&typeof x.metadata==='object'?x.metadata:{})).run();return json({data:{id:eventId,provider,status}},201)}
async function healthSummary(env:Env,tenantId:string){const [integrations,outbox,events,channels]=await Promise.all([
 env.DB.prepare(`SELECT provider,status,updated_at FROM integrations WHERE tenant_id=? ORDER BY provider`).bind(tenantId).all<any>(),
 env.DB.prepare(`SELECT status,COUNT(*) count,MAX(updated_at) last_at FROM action_delivery_outbox WHERE tenant_id=? GROUP BY status`).bind(tenantId).all<any>(),
 env.DB.prepare(`SELECT h.provider,h.component,h.status,h.latency_ms,h.message,h.observed_at FROM integration_health_events h WHERE (h.tenant_id=? OR h.tenant_id IS NULL) AND h.observed_at=(SELECT MAX(x.observed_at) FROM integration_health_events x WHERE x.provider=h.provider AND (x.tenant_id=? OR x.tenant_id IS NULL)) ORDER BY h.provider`).bind(tenantId,tenantId).all<any>(),
 env.DB.prepare(`SELECT channel_type,name,status,created_at FROM channels WHERE tenant_id=? ORDER BY channel_type,name`).bind(tenantId).all<any>()
]);
 const outboxMap=Object.fromEntries((outbox.results||[]).map((x:any)=>[x.status,Number(x.count||0)]));const byProvider=new Map<string,any>();for(const p of allowedProviders)byProvider.set(p,{provider:p,status:'unknown',source:'none',last_observed_at:null,latency_ms:null,message:null});for(const i of integrations.results||[]){const current=byProvider.get(i.provider)||{provider:i.provider};const mapped=i.status==='connected'||i.status==='active'?'healthy':i.status==='error'?'down':i.status==='disconnected'?'disconnected':'unknown';byProvider.set(i.provider,{...current,status:mapped,source:'integration',last_observed_at:i.updated_at||null})}for(const e of events.results||[]){byProvider.set(e.provider,{provider:e.provider,status:e.status,source:'health_event',component:e.component||null,last_observed_at:e.observed_at,latency_ms:e.latency_ms??null,message:e.message||null})}const queued=outboxMap.queued||0,dispatching=outboxMap.dispatching||0,failed=outboxMap.failed||0;byProvider.set('outbox',{provider:'outbox',status:failed>0?'degraded':dispatching>10||queued>50?'degraded':'healthy',source:'derived',last_observed_at:(outbox.results||[]).map((x:any)=>x.last_at).filter(Boolean).sort().pop()||null,latency_ms:null,message:failed?`${failed} falha(s) pendente(s)`:queued?`${queued} item(ns) aguardando despacho`:'Fila normal'});const providers=[...byProvider.values()];const counts=providers.reduce((a:any,p:any)=>{a[p.status]=(a[p.status]||0)+1;return a},{});return{providers,channels:channels.results||[],outbox:{queued,dispatching,sent:outboxMap.sent||0,delivered:outboxMap.delivered||0,failed},summary:{healthy:counts.healthy||0,degraded:counts.degraded||0,down:counts.down||0,disconnected:counts.disconnected||0,unknown:counts.unknown||0},generated_at:new Date().toISOString()}}
async function history(env:Env,tenantId:string,provider:string){const p=provider.toLowerCase();if(!allowedProviders.has(p))return [];const r=await env.DB.prepare(`SELECT id,provider,component,status,latency_ms,message,metadata_json,observed_at FROM integration_health_events WHERE provider=? AND (tenant_id=? OR tenant_id IS NULL) ORDER BY observed_at DESC LIMIT 100`).bind(p,tenantId).all();return r.results}
export default{async fetch(request:Request,env:Env):Promise<Response>{try{const u=new URL(request.url),method=request.method.toUpperCase(),historyMatch=u.pathname.match(/^\/api\/ops\/integration-health\/([^/]+)\/history$/);const custom=u.pathname==='/api/ops/integration-health'||u.pathname==='/api/ops/integration-health/events'||Boolean(historyMatch);if(!custom)return security.fetch(request,env);const a=await sessionFor(request,env);if(a.response)return a.response;const s=a.session||{},tenantId=s.tenant_id||env.DEFAULT_TENANT_ID;if(!tenantId)return json({error:'Tenant indisponível.'},403);if(!canViewPlatform(s))return json({error:'Sem permissão para saúde das integrações.'},403);if(u.pathname==='/api/ops/integration-health'&&method==='GET')return json({data:await healthSummary(env,tenantId)});if(u.pathname==='/api/ops/integration-health/events'&&method==='POST')return recordHealth(request,env,tenantId,s);if(historyMatch&&method==='GET')return json({data:await history(env,tenantId,decodeURIComponent(historyMatch[1]))});return json({error:'Método não permitido.'},405)}catch(e){if(e instanceof Response)return e;console.error('HML integration health error',e);return json({error:'Erro interno de saúde das integrações.'},500)}}};
