/*
 * NegocIAJá! — desenvolvido pela SER Comunicação
 * CNPJ 23.296.513/0001-97
 * Todos os direitos reservados.
 */
import {handleApi} from './api';import {handleCoreDashboard} from './core-dashboard';import {handleCoreOrders} from './core-orders';import {handleOnboarding} from './onboarding';import {handleBranding} from './branding';import {handleTeam} from './team';import {handlePlatform} from './platform';import {handleBilling} from './billing';import {handleOperations} from './operations';import {handleMarketing} from './marketing';import {handleCommerce} from './commerce';import {handleCommerceLifecycle} from './commerce-lifecycle';import {handleCommercePreferences} from './commerce-preferences';import {dispatchAbandonedCarts,handleCommerceDispatcher} from './commerce-dispatcher';import {handleCommercePostSale} from './commerce-postsale';import {handleConversations} from './conversations';import {handleEvolution} from './evolution';import {handleEvolutionInbound} from './evolution-webhook';import {handleConversationMedia} from './conversation-media';import {handleMultimodal} from './multimodal';import {handleWebchat} from './webchat';import {handleAgentApproval} from './agent-approval';import {handleAgentTools} from './agent-tools';import {handleAgentRuntime} from './agent-runtime';import {consumeAgentQueue,AgentQueueJob} from './agent-queue';import {authenticate,Env,json} from './lib';import {guardRequest,secureResponse} from './security';
const DIRECT_PRIVATE:Record<string,string>={'/app.html':'/app','/team.html':'/equipe','/super-admin.html':'/super-admin','/onboarding.html':'/onboarding','/channel-whatsapp.html':'/canal-whatsapp','/agent-actions.html':'/acoes-ia','/inbox.html':'/inbox','/plan.html':'/plano','/operations.html':'/operacoes','/marketing-admin.html':'/marketing','/commerce-insights.html':'/commerce-insights'};
async function route(request:Request,env:Env,url:URL):Promise<Response>{const direct=DIRECT_PRIVATE[url.pathname];if(direct)return Response.redirect(new URL(direct,url.origin).toString(),302);
  for(const handler of [handleMarketing,handleCommercePostSale,handleCommercePreferences,handleCommerceDispatcher,handleCommerceLifecycle,handleCommerce,handleBilling,handleEvolutionInbound,handleWebchat,handleEvolution,handleMultimodal,handleConversationMedia,handleAgentRuntime,handleAgentApproval,handleAgentTools,handleOperations,handleConversations,handlePlatform,handleTeam,handleBranding,handleOnboarding,handleCoreDashboard,handleCoreOrders,handleApi]){const r=await handler(request,env,url);if(r)return r;}
  if(url.pathname==='/'||url.pathname==='/index.html')return env.ASSETS.fetch(new Request(new URL('/landing-v2.html',url.origin),request));
  const feedbackMatch=url.pathname.match(/^\/avaliar\/([^/]+)\/?$/);if(feedbackMatch)return env.ASSETS.fetch(new Request(new URL(`/feedback.html?tenant=${encodeURIComponent(feedbackMatch[1])}&token=${encodeURIComponent(url.searchParams.get('token')||'')}`,url.origin),request));
  const shopMatch=url.pathname.match(/^\/loja\/([^/]+)\/?$/);if(shopMatch)return env.ASSETS.fetch(new Request(new URL(`/storefront.html?tenant=${encodeURIComponent(shopMatch[1])}`,url.origin),request));const chatMatch=url.pathname.match(/^\/chat\/([^/]+)\/?$/);if(chatMatch)return env.ASSETS.fetch(new Request(new URL(`/webchat.html?tenant=${encodeURIComponent(chatMatch[1])}`,url.origin),request));
  if(url.pathname==='/login'||url.pathname==='/login/'){const actor=await authenticate(request,env);if(actor)return Response.redirect(new URL(actor.role==='super_admin'?'/super-admin':'/app',url.origin).toString(),302);return env.ASSETS.fetch(new Request(new URL('/login.html',url.origin),request));}
  if(url.pathname==='/cadastro'||url.pathname==='/cadastro/')return env.ASSETS.fetch(new Request(new URL('/signup.html',url.origin),request));if(url.pathname==='/confirmar-email'||url.pathname==='/confirmar-email/')return env.ASSETS.fetch(new Request(new URL('/verify-email.html',url.origin),request));if(url.pathname==='/aceitar-convite'||url.pathname==='/aceitar-convite/')return env.ASSETS.fetch(new Request(new URL('/accept-invite.html',url.origin),request));
  if(url.pathname==='/super-admin'||url.pathname==='/super-admin/'){const a=await authenticate(request,env);if(!a)return Response.redirect(new URL('/login',url.origin).toString(),302);if(a.role!=='super_admin')return Response.redirect(new URL('/app',url.origin).toString(),302);return env.ASSETS.fetch(new Request(new URL('/super-admin.html',url.origin),request));}
  if(url.pathname==='/marketing'||url.pathname==='/marketing/'){const a=await authenticate(request,env);if(!a)return Response.redirect(new URL('/login',url.origin).toString(),302);if(a.role!=='super_admin')return Response.redirect(new URL('/app',url.origin).toString(),302);return env.ASSETS.fetch(new Request(new URL('/marketing-admin.html',url.origin),request));}
  if(url.pathname==='/onboarding'||url.pathname==='/onboarding/'){const a=await authenticate(request,env);if(!a)return Response.redirect(new URL('/login',url.origin).toString(),302);if(a.role==='super_admin')return Response.redirect(new URL('/super-admin',url.origin).toString(),302);return env.ASSETS.fetch(new Request(new URL('/onboarding.html',url.origin),request));}
  if(url.pathname==='/equipe'||url.pathname==='/equipe/'){const a=await authenticate(request,env);if(!a)return Response.redirect(new URL('/login',url.origin).toString(),302);if(a.role!=='admin')return Response.redirect(new URL('/app',url.origin).toString(),302);return env.ASSETS.fetch(new Request(new URL('/team.html',url.origin),request));}
  for(const [path,file] of [['/canal-whatsapp','/channel-whatsapp.html'],['/acoes-ia','/agent-actions.html'],['/inbox','/inbox.html'],['/plano','/plan.html'],['/commerce-insights','/commerce-insights.html']])if(url.pathname===path||url.pathname===`${path}/`){const a=await authenticate(request,env);if(!a)return Response.redirect(new URL('/login',url.origin).toString(),302);if(a.role==='super_admin'&&!a.tenantId)return Response.redirect(new URL('/super-admin',url.origin).toString(),302);return env.ASSETS.fetch(new Request(new URL(file,url.origin),request));}
  if(url.pathname==='/operacoes'||url.pathname==='/operacoes/'){const a=await authenticate(request,env);if(!a)return Response.redirect(new URL('/login',url.origin).toString(),302);if(a.role!=='super_admin')return Response.redirect(new URL('/app',url.origin).toString(),302);return env.ASSETS.fetch(new Request(new URL('/operations.html',url.origin),request));}
  if(url.pathname==='/app'||url.pathname==='/app/'){const a=await authenticate(request,env);if(!a)return Response.redirect(new URL('/login',url.origin).toString(),302);if(a.role==='super_admin'&&!a.tenantId)return Response.redirect(new URL('/super-admin',url.origin).toString(),302);return env.ASSETS.fetch(new Request(new URL('/app.html',url.origin),request));}return env.ASSETS.fetch(request);}
export default{async fetch(request:Request,env:Env):Promise<Response>{const url=new URL(request.url);try{const blocked=guardRequest(request,url);if(blocked)return secureResponse(blocked,url);return secureResponse(await route(request,env,url),url)}catch(error){console.error(JSON.stringify({event:'request_failed',path:url.pathname,error:error instanceof Error?error.message:String(error)}));return secureResponse(url.pathname.startsWith('/api/')||url.pathname.startsWith('/webhooks/')?json({error:'Erro interno.',requestId:crypto.randomUUID()},500):new Response('NegocIAJá temporariamente indisponível.',{status:500}),url)}},async queue(batch:MessageBatch<AgentQueueJob>,env:Env){await consumeAgentQueue(batch,env)},async scheduled(_controller:ScheduledController,env:Env,ctx:ExecutionContext){ctx.waitUntil(dispatchAbandonedCarts(env,env.PUBLIC_APP_URL));}};