/*
 * NegocIAJá! — desenvolvido pela SER Comunicação
 * CNPJ 23.296.513/0001-97
 * Todos os direitos reservados.
 */
import {Env,authenticate,json,audit} from './lib';

const IMAGE_TYPES=new Map([['image/png','png'],['image/jpeg','jpg'],['image/webp','webp']]);
const VIDEO_TYPES=new Map([['video/mp4','mp4'],['video/webm','webm']]);
const MAX_IMAGE=4*1024*1024,MAX_VIDEO=50*1024*1024;
const clean=(v:unknown,max:number)=>String(v??'').trim().slice(0,max);
async function asset(env:Env,key:string|null){if(!key)return null;const obj=await env.FILES.get(key);if(!obj)return null;const h=new Headers();obj.writeHttpMetadata(h);h.set('cache-control','public, max-age=3600');h.set('x-content-type-options','nosniff');return new Response(obj.body,{headers:h});}
function fallbackLogo(kind:'full'|'icon'){const svg=kind==='icon'?`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><rect width="128" height="128" rx="30" fill="#0d47a1"/><circle cx="64" cy="64" r="42" fill="#00b2ff"/><path d="M34 70h52l10-28H48l-5-12H27" fill="none" stroke="#ffb300" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/><circle cx="53" cy="92" r="7" fill="#fff"/><circle cx="83" cy="92" r="7" fill="#fff"/></svg>`:`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 780 180"><rect width="780" height="180" rx="34" fill="transparent"/><text x="20" y="122" font-family="Arial,Helvetica,sans-serif" font-size="116" font-weight="900" fill="#0d2b6f">Negoc</text><text x="340" y="122" font-family="Arial,Helvetica,sans-serif" font-size="116" font-weight="900" fill="#00b2ff">IA</text><text x="465" y="122" font-family="Arial,Helvetica,sans-serif" font-size="116" font-weight="900" fill="#ffb300">Já!</text></svg>`;return new Response(svg,{headers:{'content-type':'image/svg+xml; charset=utf-8','cache-control':'public, max-age=300','x-content-type-options':'nosniff'}});}

export async function handleMarketing(request:Request,env:Env,url:URL):Promise<Response|null>{
  const method=request.method.toUpperCase();
  if(method==='GET'&&url.pathname==='/api/public/marketing'){
    const [row,testimonials]=await Promise.all([
      env.DB.prepare(`SELECT hero_kicker,hero_title,hero_subtitle,video_title,video_description,logo_full_key,logo_icon_key,hero_video_key,hero_video_poster_key,phone_demo_key,testimonials_kicker,testimonials_title,testimonials_subtitle FROM platform_marketing WHERE id='default'`).first<Record<string,unknown>>(),
      env.DB.prepare(`SELECT id,customer_name,customer_role,company_name,quote,rating,logo_key,sort_order FROM platform_testimonials WHERE active=1 ORDER BY sort_order ASC,created_at DESC LIMIT 20`).all()
    ]);
    return json({data:{hero_kicker:row?.hero_kicker,hero_title:row?.hero_title,hero_subtitle:row?.hero_subtitle,video_title:row?.video_title,video_description:row?.video_description,logo_full_url:'/api/public/marketing/asset/logo-full',logo_icon_url:'/api/public/marketing/asset/logo-icon',hero_video_url:row?.hero_video_key?'/api/public/marketing/asset/video':null,hero_video_poster_url:row?.hero_video_poster_key?'/api/public/marketing/asset/poster':null,phone_demo_url:row?.phone_demo_key?'/api/public/marketing/asset/phone-demo':null,testimonials_kicker:row?.testimonials_kicker||'QUEM USA, RECOMENDA',testimonials_title:row?.testimonials_title||'Negócios reais. Resultados que aparecem.',testimonials_subtitle:row?.testimonials_subtitle||'Veja como o NegocIAJá! ajuda empresas a organizar o atendimento, vender melhor e manter o cliente por perto.',testimonials:(testimonials.results||[]).map((x:any)=>({...x,logo_url:x.logo_key?`/api/public/marketing/testimonial-logo?id=${encodeURIComponent(x.id)}`:null}))}});
  }
  if(method==='GET'&&url.pathname.startsWith('/api/public/marketing/asset/')){
    const kind=url.pathname.split('/').pop();const row=await env.DB.prepare(`SELECT logo_full_key,logo_icon_key,hero_video_key,hero_video_poster_key,phone_demo_key FROM platform_marketing WHERE id='default'`).first<Record<string,string|null>>();const key=kind==='logo-full'?row?.logo_full_key:kind==='logo-icon'?row?.logo_icon_key:kind==='video'?row?.hero_video_key:kind==='poster'?row?.hero_video_poster_key:kind==='phone-demo'?row?.phone_demo_key:null;const stored=await asset(env,key||null);if(stored)return stored;if(kind==='logo-full')return fallbackLogo('full');if(kind==='logo-icon')return fallbackLogo('icon');return json({error:'Arquivo não encontrado.'},404);
  }
  if(method==='GET'&&url.pathname==='/api/public/marketing/testimonial-logo'){
    const id=clean(url.searchParams.get('id'),120);const row=await env.DB.prepare(`SELECT logo_key FROM platform_testimonials WHERE id=? AND active=1 LIMIT 1`).bind(id).first<{logo_key:string|null}>();return await asset(env,row?.logo_key||null)||fallbackLogo('icon');
  }
  if(method==='GET'&&url.pathname==='/api/public/login-brand'){
    const slug=clean(url.searchParams.get('tenant'),80);if(!slug)return json({data:null});const row=await env.DB.prepare(`SELECT t.name,s.public_name,s.primary_color,s.secondary_color,s.logo_key,s.login_background_key,s.login_headline,s.login_message,s.login_button_label,s.access_show_brand FROM tenants t LEFT JOIN tenant_settings s ON s.tenant_id=t.id WHERE t.slug=? AND t.status IN ('trial','active') LIMIT 1`).bind(slug).first<Record<string,unknown>>();if(!row)return json({data:null});return json({data:{name:row.public_name||row.name,primary_color:row.primary_color||'#169CFF',secondary_color:row.secondary_color||'#0B2B7C',headline:row.login_headline||'Entre no seu painel',message:row.login_message||'Acesse atendimento, vendas e operação em um só lugar.',button_label:row.login_button_label||'Entrar',logo_url:row.logo_key?`/api/public/login-brand/asset?tenant=${encodeURIComponent(slug)}&kind=logo`:null,background_url:row.login_background_key?`/api/public/login-brand/asset?tenant=${encodeURIComponent(slug)}&kind=background`:null,show_brand:Number(row.access_show_brand??1)!==0}});
  }
  if(method==='GET'&&url.pathname==='/api/public/login-brand/asset'){
    const slug=clean(url.searchParams.get('tenant'),80),kind=url.searchParams.get('kind');const row=await env.DB.prepare(`SELECT s.logo_key,s.login_background_key FROM tenants t JOIN tenant_settings s ON s.tenant_id=t.id WHERE t.slug=? LIMIT 1`).bind(slug).first<{logo_key:string|null;login_background_key:string|null}>();const key=kind==='background'?row?.login_background_key:row?.logo_key;return await asset(env,key||null)||json({error:'Arquivo não encontrado.'},404);
  }
  if(!url.pathname.startsWith('/api/platform/marketing'))return null;
  const actor=await authenticate(request,env);if(!actor)return json({error:'Sessão ausente.'},401);if(actor.actorType!=='platform_user'||actor.role!=='super_admin')return json({error:'Acesso exclusivo do Super Admin.'},403);
  if(method==='GET'&&url.pathname==='/api/platform/marketing'){const row=await env.DB.prepare(`SELECT * FROM platform_marketing WHERE id='default'`).first();return json({data:row});}
  if(method==='PATCH'&&url.pathname==='/api/platform/marketing'){let input:any={};try{input=await request.json()}catch{};await env.DB.prepare(`UPDATE platform_marketing SET hero_kicker=?,hero_title=?,hero_subtitle=?,video_title=?,video_description=?,testimonials_kicker=?,testimonials_title=?,testimonials_subtitle=?,updated_at=datetime('now') WHERE id='default'`).bind(clean(input.hero_kicker,120),clean(input.hero_title,120),clean(input.hero_subtitle,400),clean(input.video_title,120),clean(input.video_description,500),clean(input.testimonials_kicker,120),clean(input.testimonials_title,180),clean(input.testimonials_subtitle,500)).run();await audit(env,actor,null,'platform.marketing.update','platform_marketing','default');return json({data:{ok:true}});}
  if(method==='GET'&&url.pathname==='/api/platform/marketing/testimonials'){const rows=await env.DB.prepare(`SELECT id,customer_name,customer_role,company_name,quote,rating,logo_key,active,sort_order,created_at,updated_at FROM platform_testimonials ORDER BY sort_order ASC,created_at DESC`).all();return json({data:rows.results||[]});}
  if(method==='POST'&&url.pathname==='/api/platform/marketing/testimonials'){let input:any={};try{input=await request.json()}catch{};const customerName=clean(input.customer_name,120),quote=clean(input.quote,1200);if(!customerName||!quote)return json({error:'Nome e depoimento são obrigatórios.'},400);const id=`tst_${crypto.randomUUID()}`;await env.DB.prepare(`INSERT INTO platform_testimonials (id,customer_name,customer_role,company_name,quote,rating,active,sort_order) VALUES (?,?,?,?,?,?,?,?)`).bind(id,customerName,clean(input.customer_role,120),clean(input.company_name,160),quote,Math.min(5,Math.max(1,Number(input.rating)||5)),input.active===false?0:1,Number(input.sort_order)||0).run();await audit(env,actor,null,'platform.testimonial.create','platform_testimonials',id);return json({data:{id}},201);}
  const testimonial=url.pathname.match(/^\/api\/platform\/marketing\/testimonials\/([^/]+)$/);
  if(testimonial&&method==='PATCH'){const id=decodeURIComponent(testimonial[1]);let input:any={};try{input=await request.json()}catch{};const exists=await env.DB.prepare(`SELECT id FROM platform_testimonials WHERE id=?`).bind(id).first();if(!exists)return json({error:'Depoimento não encontrado.'},404);await env.DB.prepare(`UPDATE platform_testimonials SET customer_name=?,customer_role=?,company_name=?,quote=?,rating=?,active=?,sort_order=?,updated_at=datetime('now') WHERE id=?`).bind(clean(input.customer_name,120),clean(input.customer_role,120),clean(input.company_name,160),clean(input.quote,1200),Math.min(5,Math.max(1,Number(input.rating)||5)),input.active===false?0:1,Number(input.sort_order)||0,id).run();await audit(env,actor,null,'platform.testimonial.update','platform_testimonials',id);return json({data:{ok:true}});}
  if(testimonial&&method==='DELETE'){const id=decodeURIComponent(testimonial[1]);const row=await env.DB.prepare(`SELECT logo_key FROM platform_testimonials WHERE id=?`).bind(id).first<{logo_key:string|null}>();if(!row)return json({error:'Depoimento não encontrado.'},404);await env.DB.prepare(`DELETE FROM platform_testimonials WHERE id=?`).bind(id).run();if(row.logo_key)await env.FILES.delete(row.logo_key);await audit(env,actor,null,'platform.testimonial.delete','platform_testimonials',id);return json({data:{ok:true}});}
  const testimonialLogo=url.pathname.match(/^\/api\/platform\/marketing\/testimonials\/([^/]+)\/logo$/);
  if(testimonialLogo&&method==='PUT'){const id=decodeURIComponent(testimonialLogo[1]),type=(request.headers.get('content-type')||'').split(';')[0].toLowerCase(),ext=IMAGE_TYPES.get(type);if(!ext)return json({error:'Use PNG, JPG ou WebP.'},415);const data=await request.arrayBuffer();if(!data.byteLength||data.byteLength>MAX_IMAGE)return json({error:'Arquivo deve ter no máximo 4 MB.'},413);const current=await env.DB.prepare(`SELECT logo_key FROM platform_testimonials WHERE id=?`).bind(id).first<{logo_key:string|null}>();if(!current)return json({error:'Depoimento não encontrado.'},404);const key=`platform/testimonials/${id}-${crypto.randomUUID()}.${ext}`;await env.FILES.put(key,data,{httpMetadata:{contentType:type}});await env.DB.prepare(`UPDATE platform_testimonials SET logo_key=?,updated_at=datetime('now') WHERE id=?`).bind(key,id).run();if(current.logo_key)await env.FILES.delete(current.logo_key);await audit(env,actor,null,'platform.testimonial.logo.update','platform_testimonials',id,{size:data.byteLength,type});return json({data:{ok:true}});}
  const upload=url.pathname.match(/^\/api\/platform\/marketing\/(logo-full|logo-icon|poster|video|phone-demo)$/);if(upload&&method==='PUT'){
    const kind=upload[1],type=(request.headers.get('content-type')||'').split(';')[0].toLowerCase();const isVideo=kind==='video';const ext=(isVideo?VIDEO_TYPES:IMAGE_TYPES).get(type);if(!ext)return json({error:isVideo?'Use MP4 ou WebM.':'Use PNG, JPG ou WebP.'},415);const data=await request.arrayBuffer();const max=isVideo?MAX_VIDEO:MAX_IMAGE;if(!data.byteLength||data.byteLength>max)return json({error:`Arquivo deve ter no máximo ${isVideo?'50 MB':'4 MB'}.`},413);const key=`platform/marketing/${kind}-${crypto.randomUUID()}.${ext}`;await env.FILES.put(key,data,{httpMetadata:{contentType:type}});const field=kind==='logo-full'?'logo_full_key':kind==='logo-icon'?'logo_icon_key':kind==='poster'?'hero_video_poster_key':kind==='phone-demo'?'phone_demo_key':'hero_video_key';const current=await env.DB.prepare(`SELECT ${field} old_key FROM platform_marketing WHERE id='default'`).first<{old_key:string|null}>();await env.DB.prepare(`UPDATE platform_marketing SET ${field}=?,updated_at=datetime('now') WHERE id='default'`).bind(key).run();if(current?.old_key)await env.FILES.delete(current.old_key);await audit(env,actor,null,'platform.marketing.asset.update','platform_marketing',kind,{size:data.byteLength,type});return json({data:{ok:true}});
  }
  return json({error:'Endpoint não encontrado.'},404);
}
