/*
 * NegocIAJá! — desenvolvido pela SER Comunicação
 * CNPJ 23.296.513/0001-97
 * Todos os direitos reservados.
 */
import {Env,authenticate,bytesToBase64,json,resolveTenant} from './lib';

function extractOutputText(payload:any){if(typeof payload?.output_text==='string')return payload.output_text;for(const item of payload?.output||[])for(const part of item?.content||[])if(typeof part?.text==='string')return part.text;return '';}
async function mediaRow(env:Env,tenantId:string,messageId:string){const row=await env.DB.prepare(`SELECT id,message_type,media_key,metadata_json FROM conversation_messages WHERE id=? AND tenant_id=? LIMIT 1`).bind(messageId,tenantId).first<{id:string;message_type:string;media_key:string|null;metadata_json:string}>();if(!row?.media_key)throw new Error('Mensagem não possui mídia processável.');const object=await env.FILES.get(row.media_key);if(!object)throw new Error('Mídia não encontrada no R2.');return{row,object};}

export async function transcribeMessage(env:Env,tenantId:string,messageId:string){if(!env.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY não configurada neste ambiente.');const{row,object}=await mediaRow(env,tenantId,messageId);if(row.message_type!=='audio')throw new Error('A mensagem não é áudio.');let current:any={};try{current=JSON.parse(row.metadata_json||'{}')}catch{}if(current.transcript)return{transcript:String(current.transcript),cached:true};const bytes=new Uint8Array(await object.arrayBuffer()),mime=object.httpMetadata?.contentType||'application/octet-stream';const form=new FormData();form.append('model',env.OPENAI_TRANSCRIBE_MODEL||'gpt-transcribe');form.append('file',new File([bytes],`audio-${messageId}`,{type:mime}));const r=await fetch('https://api.openai.com/v1/audio/transcriptions',{method:'POST',headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`},body:form});const data=await r.json() as any;if(!r.ok)throw new Error(data?.error?.message||'Falha na transcrição.');const transcript=String(data.text||'').trim();current.transcript=transcript;current.transcription_model=env.OPENAI_TRANSCRIBE_MODEL||'gpt-transcribe';await env.DB.prepare(`UPDATE conversation_messages SET text_content=COALESCE(NULLIF(text_content,''),?),metadata_json=? WHERE id=? AND tenant_id=?`).bind(transcript,JSON.stringify(current),messageId,tenantId).run();return{transcript,cached:false};}

export async function analyzeImageMessage(env:Env,tenantId:string,messageId:string){if(!env.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY não configurada neste ambiente.');const{row,object}=await mediaRow(env,tenantId,messageId);if(row.message_type!=='image')throw new Error('A mensagem não é imagem.');let current:any={};try{current=JSON.parse(row.metadata_json||'{}')}catch{}if(current.image_analysis)return{analysis:String(current.image_analysis),cached:true};const bytes=new Uint8Array(await object.arrayBuffer()),mime=object.httpMetadata?.contentType||'application/octet-stream';const dataUrl=`data:${mime};base64,${bytesToBase64(bytes)}`;const payload={model:env.OPENAI_VISION_MODEL||'gpt-5.6-luna',input:[{role:'user',content:[{type:'input_text',text:'Analise esta imagem enviada por um cliente em contexto comercial. Descreva objetivamente o que aparece, identifique textos visíveis, produtos/itens relevantes e sinais úteis para atendimento ou venda. Não invente detalhes.'},{type:'input_image',image_url:dataUrl}]}],store:false};const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify(payload)});const data=await r.json() as any;if(!r.ok)throw new Error(data?.error?.message||'Falha na análise da imagem.');const analysis=extractOutputText(data).trim();current.image_analysis=analysis;current.vision_model=env.OPENAI_VISION_MODEL||'gpt-5.6-luna';await env.DB.prepare(`UPDATE conversation_messages SET metadata_json=? WHERE id=? AND tenant_id=?`).bind(JSON.stringify(current),messageId,tenantId).run();return{analysis,cached:false};}

export async function preprocessInboundMessage(env:Env,tenantId:string,messageId:string){const row=await env.DB.prepare(`SELECT message_type,media_key FROM conversation_messages WHERE id=? AND tenant_id=? LIMIT 1`).bind(messageId,tenantId).first<{message_type:string;media_key:string|null}>();if(!row?.media_key)return{processed:false,type:row?.message_type||null};if(row.message_type==='audio')return{processed:true,type:'audio',...(await transcribeMessage(env,tenantId,messageId))};if(row.message_type==='image')return{processed:true,type:'image',...(await analyzeImageMessage(env,tenantId,messageId))};return{processed:false,type:row.message_type};}

export async function handleMultimodal(request:Request,env:Env,url:URL):Promise<Response|null>{const match=url.pathname.match(/^\/api\/messages\/([^/]+)\/(transcribe|analyze-image)$/);if(!match)return null;if(request.method!=='POST')return json({error:'Método não permitido.'},405);const actor=await authenticate(request,env);if(!actor)return json({error:'Sessão ausente ou expirada.'},401);const tenantId=await resolveTenant(request,env,actor);if(!tenantId)return json({error:'Selecione uma empresa para operar.'},409);try{const messageId=decodeURIComponent(match[1]);if(match[2]==='transcribe')return json({data:await transcribeMessage(env,tenantId,messageId)});return json({data:await analyzeImageMessage(env,tenantId,messageId)});}catch(error){return json({error:error instanceof Error?error.message:String(error)},400);}}
